### ISSUE TITLE
third-party input method (Chinese) problem

### ISSUE THREAD

**Issue by kenwang92** [AppHouseKitchen/AlDente-Charge-Limiter#1000]
**Is your feature request related to a problem? Please describe.**
I'm using a third-party input method (Chinese) and there is an annoying problem that I need to switch to the English input method to enter numbers in Aldente. I hope that I can set up the limit by scrolling when the cursor is on the number. Or let me add a button for customizing the number next to the limit value to make it easier to switch the limit value. Sorry for my poor English.

**Comment by MatthiasKerbl** [comment]
Hi @kenwang92,

Do you mean entering a charge limit in the pop-up window?
If that is the case, you can just use the slider to set the preferred limit.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @kenwang92,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias
