### ISSUE TITLE
Automatic Discharge causes the screen to blink

### ISSUE THREAD

**Issue by ashertz-dev** [AppHouseKitchen/AlDente-Charge-Limiter#1012]
**Describe the bug**

**To Reproduce**
1. Use external monitor. (My external display is Studio Display)
2. Close MBP build-in display
3. Battery percentage more than limit
4. Enable Automatic Discharge

**Expected behavior**
Works normally

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608) M1 Pro
 - macOS version (https://support.apple.com/en-us/HT201260) 13.5
 - AlDente Pro or AlDente Free? Pro
 - AlDente Version? 1.22.2
 - List of all enabled/disabled settings in AlDente:
   - enable
     - Stop charging when app closed 
     - Sailing Mode
     - Heat Protection
     - Stats

**Comment by MatthiasKerbl** [comment]
Hi @ashertz-dev,

Is it possible that you have the Low Power Mode setting set to "Only on Battery"?
This would mean that when Discharge is enabled, macOS thinks it is on Battery and dims the Display.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @ashertz-dev,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias
