### ISSUE TITLE
随航模式快速调节Adjust the sailing mode without recharging.

### ISSUE THREAD

**Issue by baodragon** [AppHouseKitchen/AlDente-Charge-Limiter#1019]
**Is your feature request related to a problem? Please describe.**
每次设置完航行模式差异数值后都会重置目前的电量水平，例如目前电量限制是70，随航模式差异30%，当前电量是55，如果我想要更改随航差异为25，那么电量首先会冲至70，然后再向下下跌。
Every time the differential value of the Sailing mode is adjusted, it results in a reset of the battery level. For instance, if the current battery limit is 70 and the Sailing mode differential is set at 30%, with the current battery level being 55, if I wish to change the navigation differential to 25%, then the battery level will first be charged to 70% and then drop again.

**A clear and concise description of what you want to happen.**
我希望再更改完随航模式差异数值后不要重新充电至限制水平，而是保持在当前电量不变，以减少电池的循环次数。谢谢！
I hope that after adjusting the Sailing mode differential value, the battery will not be recharged to the limit level but will remain at the current level to reduce the battery's cycle count. Thank you!

**Describe alternatives you've considered**
如果无法将其作为随航模式固定策略，至少可以提供一个开关来满足不同需求（立马充至限制电量或者保持当下电量）
If it's not possible to incorporate this as a fixed strategy in the Sailing mode, at least providing a switch could be considered to meet different needs (immediately charging to the limit battery level or maintaining the current battery level).

**Additional context**
谢谢你们的辛勤工作！Thank you for your hard work!

**Comment by MatthiasKerbl** [comment]
Hi @baodragon,

This might be a good improvement for the Sailing Mode. We will look into it.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @baodragon ,

We have just released AlDente 1.24 which includes an update for the Sailing Mode which adds this functionality. To get AlDente 1.24 you just need to update within the app under Settings/General/Check for Updates.

Best,
Matthias
