### ISSUE TITLE
Issues Arising from Performing Calibration in Power-Saving Mode

### ISSUE THREAD

**Issue by srdfjy** [AppHouseKitchen/AlDente-Charge-Limiter#1025]
1. Enable battery-saving mode and set the variance to 60. 
2. Proceed to initiate and complete the model calibration while the battery level is at 15%. 
3. At this point, a notification indicates that charging will commence only after the battery level reaches -45%.

**Comment by MatthiasKerbl** [comment]
Hi @srdfjy,

Sorry for the late reply. Also, I am not sure if I understand your issue.

1. Do you mean by "battery-saving mode" the "Low Power Mode" of macOS?
2. What exactly do you mean by "set the variance to 60"? Do you mean setting the Sailing Mode difference to 60%?
3. "Proceed to initiate and complete the model calibration while the battery level is at 15%." Do you mean starting the Calibration Mode while the current battery percentage is 15%?
4. "At this point, a notification indicates that charging will commence only after the battery level reaches -45%." Where do you see this notification?

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @srdfjy,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias
