### ISSUE TITLE
Discount

### ISSUE THREAD

**Issue by CollinGrol** [AppHouseKitchen/AlDente-Charge-Limiter#1026]
Hi there

I have your app now for some time and have also thought about upgrading to the Pro version. Then I found a GitHub chat and saw that you have made almost two years ago a -20% Black Friday Sale. Therefore I wanted to ask if there is planed  a discount in the nearer future?

Regards 
Collin

**Comment by MatthiasKerbl** [comment]
Hi @CollinGrol,

Unfortunately, there are no plans for a discount in the near future. The only discount that's available right now is the student discount at [StudentAppCentre](https://www.studentappcentre.com/App/AlDente).

Best,
Matthias
