### ISSUE TITLE
Stuck at install helper app after macos update

### ISSUE THREAD

**Issue by andrhlvk** [AppHouseKitchen/AlDente-Charge-Limiter#1030]
**Describe the bug**
After updating macOS version to the latest 13.5.1, when I try to launch Aldente, the dialog to install helper application appears. When I click "Install Helper" I'm getting stuck at the install helper dialog window with a loading cursor in an infinite loop. The modal is not clickable in any way and never goes away unless I restart the computer, it is also above all the other windows. I have tried reinstalling the app and it did not help.

**To Reproduce**
1. Update macOS to 13.5.1
2. Launch Aldente
3. Click "Install Helper" in the launch dialog
4. The app is frozen

**Expected behavior**
The app to be launched

**Screenshots**
<img width="507" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/89272850/eb6465cc-53e6-4fc2-8b2e-b0a487524dd4">

**MacBook (please complete the following information):**
 - MacBook model: MacBook Pro M1 pro 14 inch 2021 (MKGP3)
 - macOS version: 13.5.1
 - AlDente Pro or AlDente Free? Free
 - AlDente Version? 1.22.2
 - List of all enabled/disabled settings in AlDente:
 automatic updates are off, launch on boot is off

**Additional context**
Another interesting point is that my friend has the exact same setup (same aldente version, same mac, same macOS version) and everything's ok for him.

**Comment by MatthiasKerbl** [comment]
Hi @andrhlvk,

Did you try to manually uninstall the helper application following our guide [How to uninstall AlDente](https://apphousekitchen.com/how-to-uninstall-aldente-pro/)

Best,
Matthias

**Comment by andrhlvk** [comment]
> Hi @andrhlvk,
> 
> Did you try to manually uninstall the helper application following our guide [How to uninstall AlDente](https://apphousekitchen.com/how-to-uninstall-aldente-pro/)
> 
> Best, Matthias

Hello! Unfortunately I can't get to that remove option screen since the app isn't laucnhing past Install Helper state. I did try to just remove it from the finder and reinstalling though - did not help.

**Comment by andrhlvk** [comment]
> > Hi @andrhlvk,
> > Did you try to manually uninstall the helper application following our guide [How to uninstall AlDente](https://apphousekitchen.com/how-to-uninstall-aldente-pro/)
> > Best, Matthias
> 
> Hello! Unfortunately I can't get to that remove option screen since the app isn't laucnhing past Install Helper state. I did try to just remove it from the finder and reinstalling with removing associated files though - did not help.

Apparently, I did not restart my pc according to the [unisntall guide](https://apphousekitchen.com/how-to-uninstall-aldente-pro/). 

Redid the whole thing once again, without the in-app remove option and the app seems to work just fine now.

Thanks!

**Comment by wangxiang4** [comment]
The root cause of this issue is that the latest macOS system requires the
``` shell
<key>RunAtLoad</key>
<true/>
```
 to be added in order for the background process to load during the time when the Apple logo is displayed during startup. Adding this to the ```/Library/LaunchDaemons/com.apphousekitchen.aldente-pro.helper.plist``` file will ensure the process runs successfully.

**Comment by wangxiang4** [comment]
However, it is still not recommended to directly modify the ```/Library/LaunchDaemons/com.apphousekitchen.aldente-pro.helper.plist``` file because re-installing the helper will cause the changes to become invalid. It’s better to write a Daemon that will start the ```com.apphousekitchen.aldente-pro.helper``` background process during the time when the Apple logo is displayed during startup. For more details, refer to the documentation: [macos-boot-software-invalid-issue](https://github.com/wangxiang4/macos-boot-software-invalid-issue#2macos-%E9%87%8D%E5%90%AF%E5%90%8E-aldente-%E9%9C%80%E8%A6%81%E5%AE%89%E8%A3%85-helper)
