### ISSUE TITLE
During manual Discharge, Sleep is disabled after closing the lid a couple of times

### ISSUE THREAD

**Issue by ClementGre** [AppHouseKitchen/AlDente-Charge-Limiter#1036]
**Describe the bug**
When having the battery limit under the current charging level, and clicking on Discharge manually. And with all charging and sleep options disabled. The first time I close my macbook, it goes to sleep well, but when I try a second time it doesn't go to sleep (sometimes the bug occurs the third time or even after four or five tries). After this, the screen will never go off again except if you disable discharge or reach charge limit, and the Sleep menu item will be disabled in the Apple menu.

**To Reproduce**
1. Disable all charging and sleep options as followed:
<img width="300" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/51322714/a6ea2bc4-4ec1-4196-bc52-a8324bc0d153">

2. Put the charge limit at a percentage lower that the current charge
3. Click on the Discharge button :
<img width="300" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/51322714/dcd4d12a-3b0b-4ee1-b12e-2a1ddcfb01cb">

4. Try to close and reopen the lid multiple times. You might need to do this a lot of times. The bug can occur at the first try, as well as after ten tries, but this bug never appened the first time for me. Then the screen should stay always on, never going to sleep. After this, you'll notice too that the Sleep menu item is disabled in the Apple menu.

**Expected behavior**
The screen shoud be off and the mac should go to sleep as configured in the charge settings

**MacBook (please complete the following information):**
 - MacBook model: 2021 Macbook Pro M1 Pro
 - macOS version: Ventura 13.5.2
 - AlDente Pro, version 1.22.2
 - List of all enabled/disabled settings in AlDente:
<img width="250" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/51322714/caf615f9-dce9-4fef-9df7-bb34cf6034ea">
<img width="250" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/51322714/808378b7-0dfb-4fec-ad61-2722919d70ff">
<img width="250" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/51322714/b34f54e9-4f15-4064-97f0-c181885efec7">

**Comment by MatthiasKerbl** [comment]
Hi @ClementGre,

Unfortunately, I am unable to reproduce this issue. Do you still experience this issue with our newest version AlDente 1.23?
Also, could you share a debug file when this happens again? [How to generate and share a debug file](https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/)

Best,
Matthias

**Comment by ClementGre** [comment]
Hi,
I haven't noticed this issue these last few weeks, and I couldn't get to reproduce the issue with the latest version. I guess it was linked to the fact that turning off the "Disable Sleep until Charge Limit" did not have immediate effect.
But now this seems to be resolved (or maybe it was just a temporary bug of my Macbook).
Thank you !
Clément
