### ISSUE TITLE
Please add a quick toggle for low power mode on the menu bar icon.

### ISSUE THREAD

**Issue by CollinsVakayil** [AppHouseKitchen/AlDente-Charge-Limiter#1044]
Currently, the only way to activate Low Power Mode on macOS that I'm aware of is by going into the settings > battery > toggle low power mode. Which is a lot of clicks. It would be great to have a quick toggle feature to turn on low power mode from the menu bar.

**Comment by DamonHD** [comment]
I would like toi be able to control it from the AlDente scheduler.

For now I adjust it from cron autmatically as described here:

https://www.earth.org.uk/Hey-Siri-Help-Flatten-The-Duck.html#lowpowermode

Rgds

Damon

**Comment by MatthiasKerbl** [comment]
Hi @CollinsVakayil,

Good idea, there is already a feature request for this open #603. Therefore I will close this thread and post any updates in #603.

Best,
Matthias
