### ISSUE TITLE
Option to show remaining battery time and charging time

### ISSUE THREAD

**Issue by spolydor** [AppHouseKitchen/AlDente-Charge-Limiter#1050]
**Is your feature request related to a problem? Please describe.**
I am using the default battery display option too, because it shows me for how long I can use my MacBook until I need to recharge it. It is also interesting to see, how long it will need to be charged until the set charging limit.
It would be great if I/we would not need two icons in our menu bar for it.

**Describe the solution you'd like**
I would like to have the option to show the remaining battery and charging time under the charging limit/above the battery flow.

**Describe alternatives you've considered**
Maybe show it between the charging limit and the "Top-Up" Button.

**Comment by myneur** [comment]
I don't see "time remaining" there. Only "time to full", that is empty when on the battery power. 

What do I miss?
The time remaining is the only number that matters. I actually want to see  it even in the bar instead of the percents. 

This is all what I see: 
<img width="908" alt="Screenshot 2024-10-13 at 12 19 09 PM" src="https://github.com/user-attachments/assets/78ffe34f-c564-4f71-99ab-aac801b8a961">

**Comment by 5lM0N** [comment]
> I don't see "time remaining" there. Only "time to full", that is empty when on the battery power.
> 
> What do I miss? The time remaining is the only number that matters. I actually want to see it even in the bar instead of the percents.
> 
> This is all what I see: <img alt="Screenshot 2024-10-13 at 12 19 09 PM" width="908" src="https://private-user-images.githubusercontent.com/105628/376026209-78ffe34f-c564-4f71-99ab-aac801b8a961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzQ1OTMsIm5iZiI6MTcyODk3NDI5MywicGF0aCI6Ii8xMDU2MjgvMzc2MDI2MjA5LTc4ZmZlMzRmLWM1NjQtNGY3MS05OWFiLWFhYzgwMWI4YTk2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwNjM4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGNhZTIyMzlmNjYzZGEzZWQzOTFjMDFlMjY3ODk2YzI2MDVjM2FjZmJiNTA1Mjg2NWJhOWEyOThlZDAzMDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lMfU-11-o3aZKt-15pYfS9NAGrfYFWTsMRgh-vVFFb8">

Having the exact same issue on 2021 14inch MBP.

**Comment by MatthiasKerbl** [comment]
> I don't see "time remaining" there. Only "time to full", that is empty when on the battery power.
> 
> What do I miss? The time remaining is the only number that matters. I actually want to see it even in the bar instead of the percents.
> 
> This is all what I see: <img alt="Screenshot 2024-10-13 at 12 19 09 PM" width="908" src="https://private-user-images.githubusercontent.com/105628/376026209-78ffe34f-c564-4f71-99ab-aac801b8a961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjg5MjIsIm5iZiI6MTcyOTA2ODYyMiwicGF0aCI6Ii8xMDU2MjgvMzc2MDI2MjA5LTc4ZmZlMzRmLWM1NjQtNGY3MS05OWFiLWFhYzgwMWI4YTk2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwODUwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmY5YmEwY2MzNDdkYjdkYjU1NTg4MTI5NGEyNWI0ZGU1Nzk1YzFjODM1MzQ1YjkyMDY2M2U0OWU5OGE0YTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f17Y22KoB5tB2j5DwznjwKAH-ZLxTIp2geoNIs6KyC0">

Hi @myneur,

Time remaining is not yet implemented in AlDente.

Best,
Matthias

**Comment by myneur** [comment]
@MatthiasKerbl and do you already have a plan to add it? 
Would you consider even showing it directly in the status bar? 
I guess, to see how much time do I have on the battery, is even more important than any other metric. 
Thanks

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl and do you already have a plan to add it? Would you consider even showing it directly in the status bar? I guess, to see how much time do I have on the battery, is even more important than any other metric. Thanks

Hi @myneur,

Yes, we have a plan to add it but unfortunately no timeline to share at this point.

> Would you consider even showing it directly in the status bar?

Yes, that's the long-term plan.

Best,
Matthias

**Comment by mgrn0** [comment]
I would also really like to see the remaining time in the status bar.

**Comment by Tennisguy10** [comment]
Glad to find this thread. I would also love to see this as a feature. It's somewhat surprising given the already detailed display of live wattage usage in the status bat menu.

**Comment by 3urex** [comment]
Same for me. Please add the option to show live wattage and time to full/remaining time in the status bar
