### ISSUE TITLE
Removal of the top arrow/indicator on the popover

### ISSUE THREAD

**Issue by Bat-Maniac** [AppHouseKitchen/AlDente-Charge-Limiter#1055]
**Describe the solution you'd like**
In my opinion the popover would look better if the arrow/indicator at the top could be removed. This would visually adapt better to macOS popup menus.
Maybe you could make the popover a little smaller.

![Screenshot 30 09 2023 um 10 45 13 AM](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/23337032/4f213a7a-ddb2-4107-b08e-e04e4b894f64)

**Additional context**
Here is an example popover with sliders wich looks more macOS like.

![Screenshot 30 09 2023 um 10 46 05 AM](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/23337032/eb11709d-f0ed-4298-a2e1-ec41363415a2)
 _app: monitor control_

**Comment by MatthiasKerbl** [comment]
Hi @Bat-Maniac,

Good idea. We are open to changing the design of the pop-over window in one of the next updates.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @Bat-Maniac,

We have just released AlDente 1.28.1 which includes a fix for this issue. To get AlDente 1.28.1 you just need to update within the app under Settings/General/Check for Updates.
Please report back if it works for you.

Best,
Matthias
