### ISSUE TITLE
[Feature Request] Option for battery temperature in Fahrenheit

### ISSUE THREAD

**Issue by evank21** [AppHouseKitchen/AlDente-Charge-Limiter#1057]
Would be nice to have an option to show the battery temperature in fahrenheit, using something like [this converter](https://www.npmjs.com/package/celsius) maybe. Can't find any open/closed issues or FAQs about this.

**Comment by MatthiasKerbl** [comment]
Hi @evank21,

Good idea, that's definitely something we could add in a future update.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @evank21 ,

We have just released AlDente 1.25 which will automatically switch to Celsius or Fahrenheit depending on the macOS setting. To get AlDente 1.25 you just need to update within the app under Settings/General/Check for Updates.

Best,
Matthias

**Comment by sooswastaken** [comment]
Hello, could I request that this be a separate setting from the operating system (could default to sync)? Thank you.

**Comment by dvanburen** [comment]
Another vote for a user override. A simple C, F or "Follow System" option would be great.
