### ISSUE TITLE
Aldente菜单栏图标无法显示，导致无法打开界面 The Aldente menu bar icon cannot be displayed, resulting in the inability to open the interface.

### ISSUE THREAD

**Issue by jimococo** [AppHouseKitchen/AlDente-Charge-Limiter#1060]
**bug描述**
从官网下载的最新版Aldente，正常安装之后，已开启开机自启动。电脑点击关机，正常关机，盒盖，然后电脑再正常开机（不是重新启动，而是关机再开机）。开机后，Aldente软件的菜单栏图标不显示。由于Aldente软件的主界面只能从菜单栏上的图标点击唤醒，如果开机后菜单栏图标显示不出来，就无法唤出Aldente的主界面。如果在Aldente的选项里面关闭了显示dock栏图标，那么开机之后，不仅菜单栏的图标无法显示，dock栏的图标也不显示，也就没办法右键dock栏强制退出，就彻底无法唤醒Aldente的主界面了。只能去活动监视器里结束进程在打开。已尝试重新安装系统，在全新的系统下仍旧复现该bug。

After downloading the latest version of Aldente from the official website, after installing it normally, auto-starting has been enabled. The computer clicks Shut Down, shuts down normally, turns off the laptop, and then the computer turns on normally (not restarting, but turning off and on again). After turning on the computer, the menu bar icon of the Aldente software does not appear. Since the main interface of the Aldente software can only be awakened by clicking on the icon on the menu bar, if the menu bar icon does not appear after booting, the main interface of Aldente cannot be called up. If the display of dock icons is turned off in Aldente's options, not only the icons in the menu bar will not be displayed, but also the icons in the dock will not be displayed after the computer is turned on. This means that there is no way to force quit by right-clicking on the dock, and it will be completely impossible to wake up Aldente's main computer. interface. You can only go to Activity Monitor to end the open process. I have tried reinstalling the macOS system, but the bug still reappears on the new system.

**复现方法**
1. 官网正常下载安装Aldente免费版
2. 正常安装完之后，开启开机自启动，正常使用。
3. 电脑关机（不是重新启动），盒盖。
4. 开机。
5. bug出现，不显示菜单栏图标。
1. Download and install Aldente free version from the official website normally
2. After normal installation, turn on auto-start and use it normally.
3. Shut down the computer (not restart it) and close the box.
4. Turn on the computer.
5. A bug occurs and the menu bar icon is not displayed.

**期待结果**
开机后，Aldente的菜单栏图标正常出现，软件正常使用。
I expect that after booting, the Aldente menu bar icon will appear normally and the software can be used normally.

**MacBook**

 - MacBook model
MacBook Pro（13 英寸，M1，2020 年）
颜色：深空灰色
机型标识符：MacBookPro17,1
部件号：MYD83xx/A、MYD92xx/A、MYDA2xx/A、MYDC2xx/A

 - macOS version 
Sonoma 14.0

 - AlDente Pro or AlDente Free?
 Aldente free

 - AlDente Version?
 1.22.2

 - List of all enabled/disabled settings in AlDente:
开启：开机自启动
关闭：显示dock栏图标
On: Start automatically at boot
Off: Show dock icon

**Comment by MatthiasKerbl** [comment]
Hi @jimococo,

Thank you for reporting this bug. There is already an issue open for this bug (#1046). Therefore, I will close this issue and report any updates on this bug in the other issue. Also, feel free to give any update from your side about this bug in the other issue (#1046).

Best,
Matthias
