### ISSUE TITLE
Sailing mode does not work on MacOS 14

### ISSUE THREAD

**Issue by baf28** [AppHouseKitchen/AlDente-Charge-Limiter#1072]
**Describe the bug**
When the macbook discharges to 78% and connects the charger, it starts charging to the 80% limit. Before the update to macOS 14, everything worked well.

**To Reproduce**
1. Discharge macbook by 1-9%
2. connect the charger
3. Sailing mode will not work, the battery will start charging

**Expected behavior**
Before the launch, the sailing mode worked and the macbook was not charged until the charge percentage was lower than 70%

**Screenshots**
I don't know how to upload a screenshot here, sorry

**MacBook 16 M1 Pro:**
 - macOS version 14
 - AlDente Pro
 - AlDente Version 1.22.3
 - List of all enabled/disabled settings in AlDente: Sailing mode is on

**Comment by MatthiasKerbl** [comment]
Hi @baf28,

Was the Sailing Mode enabled and active while this happened? As indicated by the paper plane icon in the slider of AlDente?

<img width="472" alt="Screenshot 2023-10-16 at 09 39 28" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/33470003/e4a57455-c404-4d60-99d2-ed777c88d1bf">

Also, the Sailing Mode usually starts from the upper limit, therefore, it will always charge to the upper limit first to trigger the Sailing Mode.

Best,
Matthias

**Comment by baf28** [comment]
No, such an icon was not visible, but the mode was enabled in the settings, I checked it for sure.
<img width="472" alt="SCR-20231016-kxvq" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/42399995/6c4dd7f9-5905-4827-8caf-e80f69e5f4ed">
Everything used to work as expected, now not unfortunately (((

**Comment by baf28** [comment]
You're right, thank you. I was very worried about this moment and...
I turned off the charging, waited for 78% and turned it on. Sailing mode works!!!
<img width="472" alt="SCR-20231016-nlys" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/42399995/991ae586-b886-46ac-aa60-05f6a260719f">
Sorry to bother you, next time I'll be more restrained, I was just scared..
