### ISSUE TITLE
[Feature Request] Show power drawn by USB devices in power-flow visualisation

### ISSUE THREAD

**Issue by Jofkos** [AppHouseKitchen/AlDente-Charge-Limiter#1075]
**Is your feature request related to a problem? Please describe.**
When looking at the power flow (in the pop-up), it only differentiates between power flowing to/from the battery and power to/from the device. When plugging in an external device like, e.g., a phone, this all gets lumped under the power drawn by the system.

**Describe the solution you'd like**
An additional category of where the power flows to, representing external devices drawing power via USB/Thunderbolt (e.g., external hard drive or phone).

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by MatthiasKerbl** [comment]
Hi @Jofkos,

Great idea, we already have a feature request open for this here #1002.

Best,
Matthias

**Comment by Jofkos** [comment]
Apologies, I hadn't seen that there already was an open issue. Glad to hear someone else had the same idea!
