### ISSUE TITLE
Launch at login does not work and settings reset after restart

### ISSUE THREAD

**Issue by EMJ97** [AppHouseKitchen/AlDente-Charge-Limiter#1076]
When i reboot my mac, aldante wasn't start.
Also, Aldante's setting is reset. Manually turn on sailing mode.

MacBook model : MacBook Pro 2019 15'
macOS version: Sonoma 14
AlDente Pro
AlDente Versio: 1.22.3

**Comment by MatthiasKerbl** [comment]
Hi @EMJ97,

Do you have Launch at login enabled?
Do you have AlDente in the Login Items in the macOS settings?
Do you have AlDente enabled in the Login Items setting in macOS in the Allow in the Background list?

Please share a debug file from when you restart the MacBook but the settings have reset.

Best,
Matthias

**Comment by kapitainsky** [comment]
I have AlDente Lauch at login enabled, in Login Items and allowed in the Background list. It used to work almost perfectly until macOS upgrade to Sonoma. Now it auto starts but battery limit is always reset to 100%.

Attach my debug log:

[aldentepro-debug-2023-10-26-12:44:46.zip](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/files/13176915/aldentepro-debug-2023-10-26-12.44.46.zip)

Happy to provide any additional info it it helps solving the issue.

**Comment by alex-lechner** [comment]
I have the exact same problem! 

Also, @MatthiasKerbl I can answer all three questions with yes. I even reinstalled the app but nothing worked.
The issue came after I updated to Sonoma.

I'm on a Macbook Pro, 2,4 GHz 8-Core Intel Core i9 with 32 GB RAM, and Sonoma 14.0

**Comment by MatthiasKerbl** [comment]
Hi @alex-lechner and @EMJ97,

Thanks for sharing this issue and we are sorry you are experiencing this. We are still investigating why this is happening to some users. Also, there is already an issue open about this problem here #898. We will keep you updated about this issue there.

Best,
Matthias
