### ISSUE TITLE
Sleep Mode screen shutdown

### ISSUE THREAD

**Issue by LucyferHW** [AppHouseKitchen/AlDente-Charge-Limiter#1080]
Hey, I very like the Sleep Mode Feature. But My display does not go off when I turn on this feature.
I made a shortcut that dims the Screen to 0%, it is working but this is not perfect workflow.

Is there any option to have turned on Sleep Mode in Al Dente and that the Screens shutdowns but not the Macbook.

**Comment by MatthiasKerbl** [comment]
Hi @LucyferHW,

We are still trying to find a solution to this problem. Also, there is already a GitHub issue open for this here #998. Therefore I will close this issue.

Best,
Matthias

**Comment by LucyferHW** [comment]
@MatthiasKerbl Thank you for your response I could find the issue. :)
