### ISSUE TITLE
AlDente does not start on M3 (base, not Pro/Max) MacBook Pro late 2023

### ISSUE THREAD

**Issue by w461** [AppHouseKitchen/AlDente-Charge-Limiter#1090]
**Describe the bug**
When I click the AlDente icon nothing happens, I also do not see the process (looking for AlDente) in the activities monitor.

**MacBook (please complete the following information):**
 - MacBook model: 14" Pro late 2023 M3 
 - macOS version: 14.1.1 / was delivered yesterday with 13.5 (Ventura), same issue
 - AlDente Version: can't tell, since I cannot open. Downloaded yesterday from https://apphousekitchen.com/de/

**Comment by cartsd** [comment]
Same - MacBook Pro 14 M3 Max

**Comment by w461** [comment]
When moving files from the download folder to the new Mac I noticed an older version of AlDente Free 1.20. That one works

**Comment by sportuondo** [comment]
Same here. MacBook Pro 14" M3 Pro.

**Comment by MatthiasKerbl** [comment]
Hi everyone, 

We are working on an update to support the M3 MacBooks and hope to release it soon.

Best,
Matthias

**Comment by jamescl131** [comment]
Same 16" Macbook pro arrived today, woooo. Thanks for the help, this is a great tool.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.23 which includes a fix for this issue. To get AlDente 1.23 you just need to update within the app under Settings/General/Check for Updates.
Please report back if it works for you.

Cheers,
Matthias

**Comment by sportuondo** [comment]
@MatthiasKerbl it looks like it's working! Thank you!

**Comment by w461** [comment]
Thanks for the quick fix!
