### ISSUE TITLE
Incorrect russian translation

### ISSUE THREAD

**Issue by den-kuz** [AppHouseKitchen/AlDente-Charge-Limiter#1093]
I think i can help you translate some strings more accurate

**Screenshots**

1. 
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/15865994/7bbc9ddc-724f-41b4-89e3-369f0c333d4d)
I think you can capitalize first character here. "вид" -> "Вид"

2.
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/15865994/701cdfec-95f0-4e26-bc12-2741ee1cb2d2)

"Икона стиль" -> "Стиль иконки"
"Не показывай" -> "Не показывать"
"Альденте лого" -> "AlDente лого" (i think you can use native application name here, without translation)
"Альденте статус" -> "AlDente статус" (i think you can use native application name here, without translation)

3.
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/15865994/182e161b-6a9a-4470-b4f6-63ed6b9454af)
"Показать значок док-стации" -> "Показать значок в Dock" or "Показать значок в доке" (current tranlation looks like "Show icon in dock station")

4.
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/15865994/7a8cc60f-a2f2-4c12-988b-148bf0744dbe)

"Обвинение" -> "Зарядка" (current translation like "accusation" or "prosecution")

5.
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/15865994/4f4d3726-df2e-4ef6-88e8-0868e45c8d0a)

"Stop charging когда питание выключено" -> "Остановить заряд когда питание выключено"

6. 
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/15865994/2788b171-b649-455c-9864-b675d7922c61)

- I think you can increase window width or decrease font size here
- 1h (1 hour) = 1 ч (1 час)

**Comment by MatthiasKerbl** [comment]
Hi @den-kuz,

Thank you for helping us to improve the Russian translation.
We already have a thread and guide about improving translations over here #450. Please follow the guide and upload the improved translation file for us to implement it.

Thanks a lot,
Matthias
