### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by Haliboss** [AppHouseKitchen/AlDente-Charge-Limiter#1094]
I formatted my Macbook without deleting Aldente, does this delete Aldente? Or does it continue to run somewhere in the background?

**Comment by MatthiasKerbl** [comment]
Hi @Haliboss,

Formatting your MacBook will completely reset all changes AlDente made to your system.

Best,
Matthias

**Comment by Haliboss** [comment]
Thank you for answer.. @MatthiasKerbl
