### ISSUE TITLE
AlDente crashed and MacBook does not charge

### ISSUE THREAD

**Issue by SunsRise** [AppHouseKitchen/AlDente-Charge-Limiter#1101]
my battery is not charging now and i get this error. 
my os system is
mac big sur 11.7.10 (20G1427)
MacBook Pro mid 2014

here is the terminal.

Last login: Fri Nov 17 02:04:48 on ttys000
/Applications/AlDente.app/Contents/MacOS/AlDente ; exit;                        
m@m ~ % /Applications/AlDente.app/Contents/MacOS/AlDente ; exit;
2023-11-17 02:08:22.162 AlDente[2144:82679] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2053abdb __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20273d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20567199 CFArrayExchangeValuesAtIndices + 0
	3   libswiftCore.dylib                  0x00007fff2c791209 $ss18_CocoaArrayWrapperVyyXlSicig + 25
	4   AlDente                             0x0000000109145ce6 AlDente + 785638
	5   AlDente                             0x00000001091442e1 AlDente + 778977
	6   libswift_Concurrency.dylib          0x0000000109675286 _ZN5swift34runJobInEstablishedExecutorContextEPNS_3JobE + 70
	7   libswift_Concurrency.dylib          0x0000000109675c7d _ZL17swift_job_runImplPN5swift3JobENS_11ExecutorRefE + 77
	8   libdispatch.dylib                   0x00007fff2021e806 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff202211b0 _dispatch_continuation_pop + 423
	10  libdispatch.dylib                   0x00007fff20220887 _dispatch_async_redirect_invoke + 708
	11  libdispatch.dylib                   0x00007fff2022d818 _dispatch_root_queue_drain + 326
	12  libdispatch.dylib                   0x00007fff2022df70 _dispatch_worker_thread2 + 92
	13  libsystem_pthread.dylib             0x00007fff203c5417 _pthread_wqthread + 244
	14  libsystem_pthread.dylib             0x00007fff203c442f start_wqthread + 15
)
libc++abi: terminating with uncaught exception of type NSException
2023-11-17 02:08:22.162 AlDente[2144:82677] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2053abdb __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20273d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20567199 CFArrayExchangeValuesAtIndices + 0
	3   libswiftCore.dylib                  0x00007fff2c791209 $ss18_CocoaArrayWrapperVyyXlSicig + 25
	4   AlDente                             0x0000000109145ce6 AlDente + 785638
	5   AlDente                             0x00000001091442e1 AlDente + 778977
	6   libswift_Concurrency.dylib          0x0000000109675286 _ZN5swift34runJobInEstablishedExecutorContextEPNS_3JobE + 70
	7   libswift_Concurrency.dylib          0x0000000109675c7d _ZL17swift_job_runImplPN5swift3JobENS_11ExecutorRefE + 77
	8   libdispatch.dylib                   0x00007fff2021e806 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff202211b0 _dispatch_continuation_pop + 423
	10  libdispatch.dylib                   0x00007fff20220887 _dispatch_async_redirect_invoke + 708
	11  libdispatch.dylib                   0x00007fff2022d818 _dispatch_root_queue_drain + 326
	12  libdispatch.dylib                   0x00007fff2022df70 _dispatch_worker_thread2 + 92
	13  libsystem_pthread.dylib             0x00007fff203c5417 _pthread_wqthread + 244
	14  libsystem_pthread.dylib             0x00007fff203c442f start_wqthread + 15
)
zsh: abort      /Applications/AlDente.app/Contents/MacOS/AlDente
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by MatthiasKerbl** [comment]
Hi @SunsRise,

It seems like AlDente crashed on your system. Did you try to restart AlDente and set the charge limit to 100% so that your MacBook starts charging again?

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @SunsRise,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias
