### ISSUE TITLE
Is the Pro installation file the same as the regular version?

### ISSUE THREAD

**Issue by crackerfly** [AppHouseKitchen/AlDente-Charge-Limiter#1106]
Hi, if you have a question about AlDente, please use the Discussions section of Github: https://github.com/davidwernhart/AlDente/discussions

I have purchased the Pro license, after reinstalling the system, I always need to check the download link in the mailbox, is the installation file of the Pro version the same as the one posted on github?

**Comment by MatthiasKerbl** [comment]
Hi @crackerfly,

Yes, the installation files are the same and you can always download the latest version on our [website](https://apphousekitchen.com/pricing/) or on GitHub.

Best,

Matthias
