### ISSUE TITLE
Warming up the battery during the sleep state. 

### ISSUE THREAD

**Issue by miskiewiczm** [AppHouseKitchen/AlDente-Charge-Limiter#1114]
Hi 

I have been having a strange problem for the past few days. After putting the computer to sleep and leaving it connected to the monitor (charging via USB-C), the computer heats up while remaining asleep - the fans do not work. The battery temperature settles to more than 45 degrees. Previously, there was no such problem. There are no CPU-intensive programs running in the background. After exiting sleep mode, the system turns on the fans and the battery temperature successively decreases. 

EDIT:
Going to bed, I left the computer sedated, charged to 75% and connected to the monitor around 11:00 p.m. Around 3:00 a.m. I checked the computer was charged to 75% but remained overly warm. I unplugged it from the power supply . Around 7:00 when I opened the cover the battery was discharged to 2%.

System: Macbook Pro 2019 15.  Sonoma 14.1.1

I would appreciate your help. 

<img width="544" alt="Zrzut ekranu 2023-11-28 o 08 13 55" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/72819516/5d9d0f29-c4ae-478d-8162-5cf9a0dd9eea">
<img width="544" alt="Zrzut ekranu 2023-11-28 o 08 13 51" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/72819516/ab332d31-3ab8-4f12-adf6-fdc7686acad6">
<img width="544" alt="Zrzut ekranu 2023-11-28 o 08 13 47" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/72819516/834ab4e7-0e64-41aa-8871-b2b5ccc3d44e">

**Comment by MatthiasKerbl** [comment]
Hi @miskiewiczm,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias
