### ISSUE TITLE
After AlDente uninstallation, charging continues even when battery at 100%

### ISSUE THREAD

**Issue by Zoxjib** [AppHouseKitchen/AlDente-Charge-Limiter#1123]
After following the AlDente uninstallation FAQ page to remove the software fully, the M1 MacBook Air (2020) charges to 100%, and remains in 'charging' mode, never switching to 'plugged but not charging mode'
![](https://i.imgur.com/oKgWz05.png)

Before using AlDente when the battery reached 100%, charging stopped and the icon used to change to the below:
![](https://i.imgur.com/0eC1sLX.png)

**To Reproduce**

1. Not sure... Uninstall AlDente

**Expected behavior**
Charging should stop at 100%, revert to how it worked before AlDente

**MacBook (please complete the following information):**
 - MacBook Air M1
 - macOS version Sonoma 14.2 Public Beta, also tested on Sonoma 14.1.2 beforehand
 - AlDente Pro
 - AlDente Version 1.24
 - List of all enabled/disabled settings in AlDente: Everything disabled before uninstall

**Comment by binary-signal** [comment]
I experience the same problem, battery won't stop charging even when battery level is 100% charged

MacBook Pro 16 M1 
macOS version Sonoma 14.2.1
AlDente Pro
AlDente Version 1.24.1

**Comment by MatthiasKerbl** [comment]
Hi @Zoxjib and @binary-signal,

I have just been to an Apple Store and checked on a bunch of MacBooks that never had AlDente installed before. Every single one of them was at 100% and had the bolt icon in the battery.
![100% bolt](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/33470003/bb27a3bb-52b3-46be-93ae-0341953b5e03)

I am not sure if Apple changed it in one of the macOS updates but this means that it has nothing to do with AlDente.
Also, you don't need to worry about the battery continuing to charge at 100%. The battery management system takes care of that.

Best,
Matthias
