### ISSUE TITLE
Allow Right-Click to be optional

### ISSUE THREAD

**Issue by jnnsrctr** [AppHouseKitchen/AlDente-Charge-Limiter#1127]
As described in #1037, it is not super intuitive to have the right click directly perform an operation in the task bar.
It would be great to be able to disable this feature.

**Comment by MatthiasKerbl** [comment]
Hi @jnnsrctr,

Thank you for your input, we will consider it in the future development of AlDente. Also, since this is a duplicate of #1037 I will close this issue. 

Best,
Matthias
