### ISSUE TITLE
[bug]: install Helper

### ISSUE THREAD

**Issue by rrain7** [AppHouseKitchen/AlDente-Charge-Limiter#1135]
**Describe the bug**
After I install the latest version app, and I install Helper, but I click the icon got the message:
<img width="426" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/49144127/b9bf7585-91a7-4213-85e2-24f24c2c9689">

however, I have install the helper as before
<img width="432" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/49144127/5a4946aa-128c-455a-9dbe-49ff630304db">
 

I use Macbook Air M1, OS version:  12.6.6

**Comment by MatthiasKerbl** [comment]
Hi @rrain7,

For some updates, it is necessary to reinstall the Helper. This should be completely normal.

Best,
Matthias

**Comment by rrain7** [comment]
thanks for your reply, I have uninstall the app, and reinstall it, then install the  helper tool, but the app still notice me install the helper

step1:
<img width="426" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/49144127/c3d3fbcb-b1ac-4522-aa69-e6fc16996a8b">

step2:
<img width="341" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/49144127/be530150-b216-4c94-8ffd-cf59a29c4ccf">

but I get the info as follow:
<img width="928" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/49144127/bd59443f-10e0-401b-9f00-0bae41dc3777">

**Comment by rrain7** [comment]
I reinstall the latest version app
<img width="611" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/49144127/4a2dac80-28ff-49ef-aa83-0a7242281321">

**Comment by MatthiasKerbl** [comment]
Hi @rrain7,

Thank you for the documentation. I am not sure if I understand it correctly.
Are you experiencing a loop of the helper installation even with version 1.24.1?

Best,
Matthias

**Comment by rrain7** [comment]
> Hi @rrain7,
> 
> Thank you for the documentation. I am not sure if I understand it correctly. Are you experiencing a loop of the helper installation even with version 1.24.1?
> 
> Best, Matthias

Yes, it always tips me install the helper application even I click the [Reinstall].

Happy new Year :-)

**Comment by MatthiasKerbl** [comment]
Hi @rrain7,

Any updates on this matter?

Best,
Matthias

**Comment by rrain7** [comment]
> Hi @rrain7,
> 
> Any updates on this matter?
> 
> Best, Matthias

Hello, after I updated the app, there is no such issue. Thanks
