### ISSUE TITLE
Use Run the Calibration Mode to cause shutdown

### ISSUE THREAD

**Issue by yxd-python** [AppHouseKitchen/AlDente-Charge-Limiter#1136]
**Describe the bug**
Use Run the Calibration Mode，When the power is less than 15%, it will turn off immediately when the computer starts charging again.
My computer is a 2018 MacBookPro 15-inch，The model is A1990. macOS 13.6

**Comment by MatthiasKerbl** [comment]
Hi @yxd-python,

I am not sure I understand your issue. Do you mean that when your MacBook has less than 15% of the charge left in the battery and you plug it in, it will immediately turn off?

Best,
Matthias

**Comment by yxd-python** [comment]
No, I plugged in the power all the time and turned on the calibration mode. Under normal circumstances, when the discharge reaches 15%, it will restart charging, but at this time, the computer will suddenly shut down and restart.I just updated the latest AIDente Pro 1.24.1. I'll see if a similar situation will happen, and I will give you feedback later. Thank you.

**Comment by yxd-python** [comment]
Sorry, after my test, there is something wrong with the battery of my computer. Thank you.
