### ISSUE TITLE
I contact assist@paddle.com Gone since last night But there was no reply at all.

### ISSUE THREAD

**Issue by kimPongsakorn** [AppHouseKitchen/AlDente-Charge-Limiter#1137]
I contact assist@paddle.com Gone since last night But there was no reply at all.

I purchased the AlDente pro app, but I accidentally entered the wrong email address.

Can you help me?

**Comment by MatthiasKerbl** [comment]
Hi @kimPongsakorn,

depending on demand, the paddle support might need a couple of days to respond. Did you get an answer by now?

Best,
Matthias
