### ISSUE TITLE
About Charging

### ISSUE THREAD

**Issue by burakmorali** [AppHouseKitchen/AlDente-Charge-Limiter#1138]
When I plug in the charging cable and turn on the computer, the charge limit doesn't stay there, it goes up. I set it to 70 and it goes to 71,72 etc. and I have to lower it to the charging limit. If I open the computer immediately and plug in the charging cable, the charging limit goes down. If I do this, it goes down to the sailing mode limit and then it charges. Which way is healthier for the battery?

**Comment by MatthiasKerbl** [comment]
Hi @burakmorali,

Which MacBook model do you have?
Please keep in mind that if you have an Apple Silicon MacBook, AlDente is unable to limit charging while your MacBook is turned off. This means if you are plugging in your MacBook before it is turned on, it will charge a couple of percent until AlDente is up and running.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @burakmorali,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias
