### ISSUE TITLE
I can't buy this because of the error

### ISSUE THREAD

**Issue by 99999kcal** [AppHouseKitchen/AlDente-Charge-Limiter#1147]
I was using the free version of this app, and while using the free version of this app, I thought it was great, so I went to purchase the paid version of this app, and while purchasing it, there was an error that I couldn't do anything about. I first tried paying with Apple Pay. As you can see in the last picture, the payment didn't go through, even though I had enough money on the card linked to Apple Pay and the payment worked fine on other sites. So I tried to pay directly by entering the card number in the payment window, but again, the payment didn't go through. The second card I tried to pay with was a different card than the one linked to Apple Pay, and I had enough money on it, and it was a Mastercard, which supports international payments. Please help me. Please excuse the awkwardness of my writing, as I've turned on the translator. 

Translated with DeepL.com (free version)

<img width="830" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/153489431/0eac9f44-dc1f-4f46-9aa6-d7e1f08ffaa4">
This is the error picture I got when I tried to pay with Apple Pay.

**Comment by MatthiasKerbl** [comment]
Hi @99999kcal,

I am sorry to hear that you are having an issue with paying on our website.
Please contact the support team of our payment provider Paddle at [assist@paddle.com](mailto:assist@paddle.com). The Paddle support will try to solve your issue as fast as possible.

Best,
Matthias
