### ISSUE TITLE
Licence key is not working

### ISSUE THREAD

**Issue by Tito28100** [AppHouseKitchen/AlDente-Charge-Limiter#1148]
Hello

I just purchased a new MacBook Pro and sold the old one. So I would like to install Aldente pro that I purchased, with my license key, but it doesn’t work.
It says that it is already used. But I have sold the old MacBook, Aldente pro is not used anymore on this old laptop !
Please help

![GraphiqueColl?-1](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/156577125/3e36a25c-81b4-46fc-adf2-ffb0b0c0dab5)

Rgds

**Comment by MatthiasKerbl** [comment]
Hi @Tito28100 and @emreozden1995,

Please take a look at the following part from our FAQ:

**What happens to my license when I get a new MacBook?**
No worries, you can take your license to your new MacBook. Just deactivate your license on the old MacBook and activate it on your new one.

If you forgot to deactivate your license on your old MacBook, you need to contact the support team of our merchant of record Paddle at [assist@paddle.com.](mailto:assist@paddle.com)

Best,
Matthias
