### ISSUE TITLE
Sailing mode doesnt discharge

### ISSUE THREAD

**Issue by jemitoburt** [AppHouseKitchen/AlDente-Charge-Limiter#1150]
Hello, I've been using Al Dente for a while but I always had issues with Sailing mode and discharging on my Mac. I've reinstalled Helper several times. Tried turning off and on sailing mode. I changed the difference percentage but nothing worked so far for me. The plane icon is displayed in a popup window but it's not discharging. It's staying at 70% all the time so I have to unplug it manually.

Macbook pro touchbar M2 2022
Al Dente Pro 1.24.1
Sonoma 14.2.1
![Xnip2024-01-19_12-40-47](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/72654834/04a754ab-7b7c-473f-8d82-3e7def14090c)
![Xnip2024-01-19_12-40-33](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/72654834/b157e58c-b35d-4384-b7bf-98b6b734e8f8)

Thanks for any help

**Comment by MatthiasKerbl** [comment]
Hi @jemitoburt,

This is the intended behavior of the Sailing Mode and looking at your screenshots, Sailing Mode is working as intended.
It is a common misconception that the Sailing Mode does actively charge and discharge your MacBook between the sailing range. This would be much worse for the battery.
You can read a detailed description of what the Sailing Mode does on our blog "[Feature Explanation: Sailing Mode](https://apphousekitchen.com/feature-explanation-sailing-mode/)"

Best,
Matthias

**Comment by jemitoburt** [comment]
Thanks for the response. But is it possible to display the actual battery level instead of keeping the display at 70%?

**Comment by MatthiasKerbl** [comment]
> Thanks for the respond. But is it possible to display the actual battery level instead of keeping the display at 70%?

Yes, please see the settings in the screenshot below:
<img width="544" alt="Setting" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/33470003/e541b358-38f1-4267-aece-daec744ff0f0">

Best,
Matthias
