### ISSUE TITLE
Cannot update: Error

### ISSUE THREAD

**Issue by martin-braun** [AppHouseKitchen/AlDente-Charge-Limiter#1163]
**Describe the bug**
An error occurred... (please see the screenshot)

**To Reproduce**
Wait for the update notice.

**Expected behavior**
Should update.

**Screenshots**
<img width="431" alt="Screenshot 2024-02-10 at 19 13 03" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/33c7cbab-ddef-45da-b373-7f9ef2c1190c">

**MacBook (please complete the following information):**
 - MacBook model MacBook Pro 16-inch, 2019
 - macOS version 13.5.2 (22G91)
 - AlDente Pro
 - AlDente Version 1.24.1

<details>
<summary>List of all enabled/disabled settings in AlDente:</summary>
<img width="452" alt="Screenshot 2024-02-10 at 19 15 16" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/095793da-42f1-485b-9e0c-156593c41ace">
<img width="450" alt="Screenshot 2024-02-10 at 19 15 20" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/c5c695cd-3db7-4d38-8c97-97e17572442c">
<img width="455" alt="Screenshot 2024-02-10 at 19 15 24" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/b39220e4-6222-4502-9d02-69a8b26352c3">
<img width="455" alt="Screenshot 2024-02-10 at 19 15 28" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/1bdabd77-89e3-4bfc-ad58-4cdf915d6c45">
<img width="450" alt="Screenshot 2024-02-10 at 19 15 32" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/e95a1f9f-49ce-4e93-aa55-62044361b7e8">
<img width="453" alt="Screenshot 2024-02-10 at 19 15 36" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/841f12bd-cff2-47d7-9db2-8d36f10c4085">
</details>

**Additional context**

Also noticed this:
![2024-02-10 19 11 01](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/c4518cf0-8b03-4a83-93c9-f1d4020fbbb4)
Funny™️

**Comment by MatthiasKerbl** [comment]
Hi @martin-braun,

We have already fixed this issue and are not able to reproduce it anymore.
Do you still experience this issue?

Best,
Matthias

**Comment by martin-braun** [comment]
Good job, it's fixed, thanks.
