### ISSUE TITLE
Popover Missing Stats

### ISSUE THREAD

**Issue by itsfatal** [AppHouseKitchen/AlDente-Charge-Limiter#1174]
**MacBook (please complete the following information):**
 - MacBook Model: MacBook Pro (14-inch, 2021)
 - macOS Version: 14.3.1
 - AlDente Pro or AlDente Free: Pro
 - AlDente Version: 1.25.2
 
I'm not seeing these stats in the popover for some reason. 
![4480](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/14064875/479e8b22-1561-4847-ade6-9541a93812bf)
<img width="402" alt="92116" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/14064875/0c0c1ff0-1545-4844-823e-ae62a473f14d">

**Comment by MatthiasKerbl** [comment]
Hi @itsfatal,

You have to open each category by clicking on the downward facing error to enable them in the popover.

Best,
Matthias

**Comment by itsfatal** [comment]
Ahhh it will reflect whichever sections i have expanded. Apologies. Thank you!

**Comment by vladcudoidem** [comment]
Hi @MatthiasKerbl,

not gonna lie, this is very unintuitive. A simple fix would be to replace the up/down arrows on the top-right corner of each category with toggles, like the one next to "Show in Popover". As far as I can tell, no UI behaviour would have to be changed, only a view.

1. You can only click on the arrows anyway (clicking anywhere else on those card views does nothing).
2. Toggles have exactly the same number of states as the arrows, namely 2. So the change would be: **_arrow down -> toggle off_** & **_arrow up -> toggle on_**.

Does that make sense?

Greetings
Vlad

**Comment by MatthiasKerbl** [comment]
> Hi @MatthiasKerbl,
> 
> not gonna lie, this is very unintuitive. A simple fix would be to replace the up/down arrows on the top-right corner of each category with toggles, like the one next to "Show in Popover". As far as I can tell, no UI behaviour would have to be changed, only a view.
> 
> 1. You can only click on the arrows anyway (clicking anywhere else on those card views does nothing).
> 2. Toggles have exactly the same number of states as the arrows, namely 2. So the change would be: **_arrow down -> toggle off_** & **_arrow up -> toggle on_**.
> 
> Does that make sense?
> 
> Greetings Vlad

Hi @vladcudoidem,

Thank you for your feedback and your suggestions. We will consider it and try to improve it in one of the upcoming updates.

Best,
Matthias
