### ISSUE TITLE
Why does it automatically increase the charging limit to 100%?

### ISSUE THREAD

**Issue by LisonFan** [AppHouseKitchen/AlDente-Charge-Limiter#1189]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608): MacBookPro18,1
 - macOS Version (https://support.apple.com/en-us/HT201260): 14.4
 - Charger Model (Apple, Third Party, Wattage,...): Third Party PD 100W
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): USB-C
 - AlDente Pro or AlDente Free: AlDente Pro (Setapp)
 - AlDente Version: 1.25.2
 - List or add screenshots of all enabled/disabled settings in AlDente:
 
<img width="432" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/9424775/1625f110-f9e5-46a0-bee0-425c32a76579">
<img width="432" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/9424775/8e344edc-0144-4dd8-815e-343418dd6c4d">
<img width="432" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/9424775/9d915c64-a45a-4a39-ae0b-bfb43701be3d">

 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
[aldentepro-debug-2024-03-12-23:42:44.zip](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/files/14575153/aldentepro-debug-2024-03-12-23.42.44.zip)
Unzip password: GeiH5Wjg

 - External Monitor connected? YES
 - MacBook used in Clamshell Mode (with the lid closed)? Open

**Describe the bug**
Without any operation, I don’t know when the charging limit was raised to 100%.

**Screenshots and Screen Recordings**
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/9424775/d11449fd-8dd5-4a76-89e0-8f78fa7143ef)

**Comment by MatthiasKerbl** [comment]
Hi @LisonFan,

Unfortunately, we can not see any irregularities in your debug file. If possible, please generate a new debug file directly after the charge limit changes to 100%.
Is it possible that you used the Top Up or Right Click feature accidentally to change the charge limit to 100%?
You can read more about these features on our [website](https://apphousekitchen.com/).

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
> > Hi @LisonFan,
> > Unfortunately, we can not see any irregularities in your debug file. If possible, please generate a new debug file directly after the charge limit changes to 100%. Is it possible that you used the Top Up or Right Click feature accidentally to change the charge limit to 100%? You can read more about these features on our [website](https://apphousekitchen.com/).
> > Best, Matthias
> 
> I probably know the reason. I just found out that right-clicking on AlDente in the menubar changes the charging limit.
> 
> Can a configuration option be added in settings? It should allow disabling this feature.

Hi @LisonFan,

Yes, this might be the reason, and the good news with the next update, you will be able to disable the Right Click setting.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Also, there is already an issue about this open here #1037. Therefore, I will close this issue and give updates in the other one.

Best,
Matthias
