### ISSUE TITLE
Show the current battery percentage in the menubar icon

### ISSUE THREAD

**Issue by beyondcompute** [AppHouseKitchen/AlDente-Charge-Limiter#1194]
Hello! I understand that AlDente Pro has [live status icons](https://apphousekitchen.com/feature-explanation-live-status-icons/). Would it be feasible to make a live status icon mode that shows the percentage inside the icon? That would allow me to “save space” in the menubar. I would hide the builtin MacOS icon and have the percentage visible at a glance. (Now I have the AlDente icon, the builtin battery icon *and* the percentage next to it. Which all together occupies more space.)

Thank you!

**Comment by MatthiasKerbl** [comment]
Hi @beyondcompute,

Great idea, we will try to add the iOS icon type in one of the future updates.
Since there is already a request for this open I will close this issue and give updates at issue #1041.

Best,
Matthias
