### ISSUE TITLE
The settings window won't close with Cmd+W unlike most Mac apps

### ISSUE THREAD

**Issue by IAmVisco** [AppHouseKitchen/AlDente-Charge-Limiter#1199]
**Is your feature request related to a problem? Please describe.**
The title should be self-explanatory. Cmd+Q quits the app properly, but Cmd+W does nothing with the settings window.

**Comment by MatthiasKerbl** [comment]
Hi @IAmVisco,

We have just released AlDente 1.27 which now supports closing the settings window with cmd+w.

Best,
Matthias

**Comment by IAmVisco** [comment]
Great, thanks!
