### ISSUE TITLE
Charging past set limit

### ISSUE THREAD

**Issue by Lasvad** [AppHouseKitchen/AlDente-Charge-Limiter#1202]
**MacBook (please complete the following information):**
 - MacBook Model 15inch, 2019
 - macOS Version (https://support.apple.com/en-us/HT201260): 14.4
 - Charger Model (Apple, Third Party, Wattage,...): Apple
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): Apple USB-C
 - AlDente Pro or AlDente Free: Free
 - AlDente Version: 1.25.2
 - List or add screenshots of all enabled/disabled settings in AlDente:
 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected? No
 - MacBook used in Clamshell Mode (with the lid closed)? No

**Describe the bug**

Charging past limit 
Went to 90% (screenshot is 85% as some time has past)
<img width="299" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/9116207/8617aa5f-6a3d-41c0-9080-8e2d004c7045">

Limit was set to 80%
<img width="398" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/9116207/12dafc42-5b91-43c7-8974-17b5b10a850b">

Manage battery longevity is enabled. maybe cause of this since if Mac is fake reporting percentages by 10%, indicating 100% when really 90% is charged, if AlDante doesn't use this fake value but the relies on the real value, AlDante might change to 80% of current total capacity while Mac reports this as 90%
<img width="477" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/9116207/cf14729f-6a40-4720-8d0c-d00a0367f181">

**To Reproduce**
1. Set limit to 80
2. Charge
3. Charged to 90%

**Expected Behavior**
Should not charge more then 80%

**Comment by amlboeton** [comment]
yup this happened to my Ventura 13.6.7 as well

**Comment by MatthiasKerbl** [comment]
Hi @Lasvad,

We have just released AlDente 1.27 which has big changes under the hood for Intel-based MacBooks. This should also make the charge limit more accurate.

Best,
Matthias
