### ISSUE TITLE
sailing mode not working

### ISSUE THREAD

**Issue by kasteph** [AppHouseKitchen/AlDente-Charge-Limiter#1205]
**MacBook (please complete the following information):**
 - MacBook Model: MacBook Air M2 13"
 - macOS Version: 14.4.1 (23E224)
 - Charger Model (Apple, Third Party, Wattage,...): Apple
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): MagSafe 3
 - AlDente Pro or AlDente Free: AlDente Pro
 - AlDente Version: 1.25.2
 - List or add screenshots of all enabled/disabled settings in AlDente:
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3408478/1ebd2d3f-20d6-4cd8-b6b3-cce7d14fd221)
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3408478/3e3cefff-760e-40d7-9a22-159a6d46b91b)

 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected? Yes
 - MacBook used in Clamshell Mode (with the lid closed)? Yes

**Describe the bug**

**To Reproduce**
1. Go to Features
2. Enable Sailing Mode

**Expected Behavior**
It should "sail" down to 30% and the charge to 70% but it doesn't happen.

**Screenshots and Screen Recordings**
![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3408478/8eb06ff7-7eba-4f03-b008-3391da96c3bf)
I can see the sailing mode icon but it really hasn't sailed.

![image](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3408478/f334cec9-440a-4772-9c52-c316518d6188)

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @kasteph,

This is the intended behavior of the Sailing Mode and looking at your screenshots, Sailing Mode is working as intended.
It is a common misconception that the Sailing Mode does actively charge and discharge your MacBook between the sailing range. This would be much worse for the battery.
You can read a detailed description of what the Sailing Mode does on our blog "[Feature Explanation: Sailing Mode](https://apphousekitchen.com/feature-explanation-sailing-mode/)"

Best,
Matthias
