### ISSUE TITLE
Heat protection bug

### ISSUE THREAD

**Issue by mustthink** [AppHouseKitchen/AlDente-Charge-Limiter#1213]
**MacBook:**
 - MacBook Model MBP 2021 16":
 - macOS Version Sonoma 14.4.1:
 - Charger Model (Apple, Third Party, Wattage,...):
 - Charging Cable MagSafe 3:
 - AlDente Pro:
 - AlDente Version: 1.25.2
 - External Monitor connected? No
 - MacBook used in Clamshell Mode (with the lid closed)? No

**Describe the bug**
Heat protection doesn't work when activate Top Up. Battery can heat more than 36 C. 

**To Reproduce**
1. Turn on "Top Up"
2. Wait for battery heating 

**Expected Behavior**
Battery heat protection should work in Top Up mode.

**Comment by MatthiasKerbl** [comment]
Hi @mustthink,

The Top Up feature is usually used when people need to quickly charge their MacBook to 100% for a trip without access to a plug. Therefore, the Heat Protection feature is deactivated during Top Up to not increase the charging time.
If you want the Heat Protection feature to stay active when you charge to 100%, just manually change the Charge Limit to 100%.

Best,
Matthias
