### ISSUE TITLE
Charge limit changes "on it's own".

### ISSUE THREAD

**Issue by elihollander** [AppHouseKitchen/AlDente-Charge-Limiter#1215]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608): M1 Pro Max 16"
 - macOS Version (https://support.apple.com/en-us/HT201260): 14.4.1
 - Charger Model (Apple, Third Party, Wattage,...): Apple
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): Apple
 - AlDente Pro or AlDente Free: Pro
 - AlDente Version: 1.26.1
 - List or add screenshots of all enabled/disabled settings in AlDente: Charging—all enabled; Sleep—all disabled; Sailing Mode—enabled 10%; heat protection—enabled; low power mode—disabled; 
 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected? yes
 - MacBook used in Clamshell Mode (with the lid closed)? no

**Describe the bug**
I set the charge limit 56% and twice I have notice that the charge limit "changed" on its own to 51%
**To Reproduce**
Steps to reproduce the behavior: I have not been able to reproduce this

**Expected Behavior**
I don't expect Al Dente Pro to change such a setting
**Screenshots and Screen Recordings**
If applicable, add screenshots or screen recordings of the issue to help explain your problem.

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @elihollander,

Please generate and share a debug file the next time this happens so that we can assess this issue better.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @elihollander,

Any update on this matter?

Best,
Matthias

**Comment by elihollander** [comment]
Hello Matthias,

No… that problem hasn’t occurred again. Perhaps it was “something” I inadvertently did. 

Overall, I really like your software and I have been recommending it to others (who have gone ahead and purchased the software). 

Thank you,

Eli


_____________________________________________________________

Eli Hollander, Professor Emeritus        831.464.0616 (voice)
   Film and Digital Media Department     
   University of California, Santa Cruz                                             
   Santa Cruz, CA  95064
***@***.***
http://film.ucsc.edu/

￼

_____________________________________________________________
