### ISSUE TITLE
The Helper installation is not accepting my icloud password or the laptop password.

### ISSUE THREAD

**Issue by MANJIT122** [AppHouseKitchen/AlDente-Charge-Limiter#1221]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608): Apple M1 Pro
 - macOS Version (https://support.apple.com/en-us/HT201260): 14.4.1
 - Charger Model (Apple, Third Party, Wattage,...): Original 
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...):
 - AlDente Pro or AlDente Free: Free 
 - AlDente Version: 1.26.1
 - List or add screenshots of all enabled/disabled settings in AlDente:
 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected? no
 - MacBook used in Clamshell Mode (with the lid closed)? n

**Describe the bug**

**To Reproduce**

**Expected Behavior**

**Screenshots and Screen Recordings**
If applicable, add screenshots or screen recordings of the issue to help explain your problem.

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @MANJIT122,

to permit AlDente to install the helper application you need to enter your macOS user password. You can check if you are using the correct password by restarting your MacBook. Upon restart you need to enter the same password you need to enter while installing the helper application.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @MANJIT122,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias
