### ISSUE TITLE
Sailing Mode reverts to -5 on input

### ISSUE THREAD

**Issue by KrzysztofPrzygoda** [AppHouseKitchen/AlDente-Charge-Limiter#1224]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608): MBP M1 Max
 - macOS Version (https://support.apple.com/en-us/HT201260): 14.4.1
 - Charger Model (Apple, Third Party, Wattage,...): Apple
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): MagSafe 3
 - AlDente Pro or AlDente Free: Pro
 - AlDente Version: 1.26.1
 - List or add screenshots of all enabled/disabled settings in AlDente:
 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected? Yes
 - MacBook used in Clamshell Mode (with the lid closed)? No

**Describe the bug**
Sailing Mode always reverts to `-5` on any user input.

**To Reproduce**

**Expected Behavior**
Sailing Mode accepts user input.

**Screenshots and Screen Recordings**
If applicable, add screenshots or screen recordings of the issue to help explain your problem.

<img width="544" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/32018059/41fed816-13db-45f1-8904-0881172353e7">

**Additional context**

MacBook is in calibration mode.

**Comment by MatthiasKerbl** [comment]
Hi @KrzysztofPrzygoda,

Thanks for making us aware of this bug. We will fix it with one of the upcoming updates.

Best,
Matthias
