### ISSUE TITLE
Aldente broke something with my MB Pro Battery?? Not charging through USB-C when connected to a Monitor anymore!!! 

### ISSUE THREAD

**Issue by hansolowireless** [AppHouseKitchen/AlDente-Charge-Limiter#1232]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608):
 M2 Pro

 - macOS Version (https://support.apple.com/en-us/HT201260):
 Sonoma 14.5

 - Charger Model (Apple, Third Party, Wattage,...):
 LG Monitor

 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...):
 Usb-C

 - AlDente Pro or AlDente Free:
 Free

 - AlDente Version:
 Latest as of this date

 - List or add screenshots of all enabled/disabled settings in AlDente:

<img width="427" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/23506001/b9c5db0f-7824-48d7-8207-9029faa0172f">

 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 
 - External Monitor connected?
   Charging through external monitor

 - MacBook used in Clamshell Mode (with the lid closed)?
 Lid open

**Describe the bug**
Uninstalled Aldente Free and now my Macbook Pro does not seem to charge when connected to a USB-C charging monitor. It charges if connected to a brick. It was working fine before installing Aldente.

**To Reproduce**
1. Install Aldente on a MB Pro M2 charging through USB-C connected to a power-supplying monitor
2. Uninstall Aldente following the instructions
3. MB Pro does not charge anymore when connected to the monitor. It recognizes it as a power supply, but charge percentage won't go up anymore and the battery will effectively not charge. Charges fine with the power brick.

**Expected Behavior**
Macbook should charge when connected to the monitor.

**Screenshots and Screen Recordings**
If applicable, add screenshots or screen recordings of the issue to help explain your problem.

**Additional context**

**Comment by Kief5555** [comment]
You need to uninstall the helper if you havent already.

**Comment by hansolowireless** [comment]
Nvm, may be due to another cause, but I thought Al Dente was the issue. 

You can close this ticket for now. Thanks.
