### ISSUE TITLE
Fixed-Layout Flow Chart for Better Power Flow Visualization

### ISSUE THREAD

**Issue by Plokkke** [AppHouseKitchen/AlDente-Charge-Limiter#1236]
**Is your feature request related to a problem?**
I find it frustrating that the current flow chart representation in AlDente changes its layout depending on whether the MacBook is plugged in or not. The battery sometimes appears on the left as a source, on the right as a destination, or not at all when it is full or paused. This dynamic layout makes it difficult to quickly understand the current status of the battery and power flow.

**Describe the solution you’d like**
I would like to suggest a fixed-layout graphical representation where each entity (battery, charger, MacBook) has a consistent position on the chart. In this static layout, the flow of energy would move between these entities, clearly indicating whether the battery is receiving or providing energy and whether the MacBook is charging or not. This would provide an immediate visual understanding of the power status at a glance.

Thank you for considering this enhancement to AlDente.

**Comment by MatthiasKerbl** [comment]
Hi @Plokkke,

Thank you for your feedback. However, in our opinion, it is better to have the direction of the "energy flow" constant and change the sources and consumers of energy accordingly. Therefore, it is immediately visible if for example the battery is being drained or charged depending on if it is on the right or left side.

Best,
Matthias
