### ISSUE TITLE
Bootcamp charges always to full capacity since 1.27

### ISSUE THREAD

**Issue by quasiDigi** [AppHouseKitchen/AlDente-Charge-Limiter#1250]
**MacBook (please complete the following information):**
 - MacBook Model: MacBook Pro (15-inch, 2018):
 - macOS Version: 14.5 (23F79)
 - Charger Model: Third Party (Glyph TB3 dock)
 - Charging Cable: Third Party (TB3 cable)
 - AlDente Pro or AlDente Free: Free
 - AlDente Version: 1.27
 - List or add screenshots of all enabled/disabled settings in AlDente:
![Screenshot 2024-06-23 at 17 18 27](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/26095252/5f6986f9-83d7-4a89-949e-a886aaf9a237)
![Screenshot 2024-06-23 at 17 18 36](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/26095252/3988bb5a-493b-44a5-adbe-dcb5d0aa38d9)
![Screenshot 2024-06-23 at 17 18 42](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/26095252/b66ec1ee-31f7-4062-95ba-35b98cbfbe61)
![Screenshot 2024-06-23 at 17 18 49](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/26095252/b87477ee-19b0-48a1-8a16-a64d39591259)
![Screenshot 2024-06-23 at 17 18 56](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/26095252/d7a23c96-55e9-43fb-bc76-d8edbee2aa58)
![Screenshot 2024-06-23 at 17 19 03](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/26095252/d9e2e0c9-ca1e-40d7-8fe6-5117c02d187d)

 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected? Yes
 - MacBook used in Clamshell Mode (with the lid closed)? No

**Describe the bug**

**To Reproduce**
1. Set AlDente to 77%
2. Use Discharge option to empty battery to 77%
3. Restart computer in Windows (Bootcamp)
4. Use it for a while
5. Restart in macOs
6. Check battery status
7. See it's at 100% 

**Expected Behavior**
The battery charge was expected to stay at 77%

**Screenshots and Screen Recordings**
–

**Additional context**
–

**Comment by 8fdafs2** [comment]
> Unified the charging backend for all MacBooks with Intel CPUs. This means that "Stop charging when sleeping" and "Stop charging when powered off" are no longer required on these devices because the charge limit remains in these scenarios. This also means that "Intel Mode" is gone for good, since it is not needed anymore. For more info, please visit our [blog](https://apphousekitchen.com/adding-aldente-pro-support-to-16-new-intel-macbook-models-full-list-below/).

It appears that in version 1.27, the unified backend has a bug that causes Intel MacBooks to sometimes charge to 100%?

**Comment by MatthiasKerbl** [comment]
Hi @quasiDigi and @8fdafs2,

Due to the unified charging backend and our attempt to streamline the user experience of AlDente throughout all MacBook models, the Intel Mode is gone now, and the automatic persistent charge limit is therefore only available with AlDente Pro. Suppose you want the charge limit to persist during Bootcamp. In that case, you can consider getting AlDente Pro for the automatic persistent charge limit or downgrading to AlDente 1.26.1 and continue manually using the Intel Mode.
You can get AlDente Pro on our [website](https://apphousekitchen.com/) and AlDente 1.26.1 on [GitHub](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/releases/tag/1.26.1).

Best,
Matthias

**Comment by quasiDigi** [comment]
Thank you for your prompt answer. You might adapt your documentation, as this aspect is very unclear. Just adding your paragraph would solve it.

**Comment by quasiDigi** [comment]
Solution proposed by @MatthiasKerbl , closing the ticket
