### ISSUE TITLE
Add visual indicator for LPM ON status in the menubar

### ISSUE THREAD

**Issue by amit-bh** [AppHouseKitchen/AlDente-Charge-Limiter#1255]
Currently you can use the helpful shortcut of right click on menubar icon to toggle LPM. It would be helpful to have a visual indicator visible on the menu icon to indicate LPM ON status. Otherwise one has to click the popover to view the LPM status. Thanks for the consideration!

**Comment by MatthiasKerbl** [comment]
Hi @amit-bh,

We have just released AlDente 1.28.1 which adds a setting to tint the menubar icon if the Low Power Mode is enabled. To activate this feature, open the AlDente Settings go to Appearance/Menubar Icon/Low Power Mode Tint, and enable it. To get AlDente 1.28.1 you just need to update within the app under Settings/General/Check for Updates.
Please report back if it works for you.

Best,
Matthias
