### ISSUE TITLE
Menu Bar Icon: Indicate Low Power-Mode

### ISSUE THREAD

**Issue by martin-braun** [AppHouseKitchen/AlDente-Charge-Limiter#1266]
**Is your feature request related to a problem? Please describe.**
I can't see if I'm currently on Low Power mode or not.

**Describe the solution you'd like**
Any visual indicator that I am on Low Power mode in the menu bar.

**Describe alternatives you've considered**
Just toggling it once or twice reveals the mode as Low Power mode will dimm the screen, but it's not a great solution. I also installed another app to indicate the mode, but it would fail to pickup changes made by AlDente until I would interact with it.

**Additional context**
Not sure how it could be solved, but I would love to have support for the AlDente battery icon with percentage display:

<img width="76" alt="image" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/24259245/214ffaa7-9052-42f8-9359-9060423f003e">

Thanks a lot!

**Comment by Volodymyr-13** [comment]
@MatthiasKerbl 

Same here, this is just so easy to implement. 

Same as for iOS. 
![Screenshot 1](https://github.com/user-attachments/assets/83b7192d-bd2e-4e36-a641-88e964dbe2e4)
