### ISSUE TITLE
Battery is charging over the set limit 

### ISSUE THREAD

**Issue by TaylorSwift1803** [AppHouseKitchen/AlDente-Charge-Limiter#1271]
Hi, I set the limit to 65% and then I used my Mac with power adapter plugged in. It was normal for about 2 hours (I mean the battery stayed at the same percentage with the limit charge which was 65%). But then the battery charged to 66%. I just browsed the Internet, no editing, no sleeping, no lip closed during this time, just constantly opened. I’m so worried whether it was normal. And how to fix/avoid it?

 - MacBook Air M3
 - macOS Version: Sonoma 14.5
 - Charger Model: Apple, 30W
 - Charging Cable: MagSafe 3
 - AlDente Free latest version 
 - External Monitor connected: no
 - MacBook used in Clamshell Mode: no

**Comment by MatthiasKerbl** [comment]
Hi @TaylorSwift1803,

This is completely normal. Unfortunately, we cannot guarantee that your battery will stay exactly at the charge limit for various technical reasons. However, in AlDente Pro we have implemented a feature called Automatic Discharge which will automatically discharge the battery to the charge limit again if it ever jumps above the limit.

Best,
Matthias
