### ISSUE TITLE
Unable to install helper

### ISSUE THREAD

**Issue by kuyvub** [AppHouseKitchen/AlDente-Charge-Limiter#1272]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608):
 - macOS Version (https://support.apple.com/en-us/HT201260):
 - Charger Model (Apple, Third Party, Wattage,...):
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...):
 - AlDente Pro or AlDente Free:
 - AlDente Version:
 - List or add screenshots of all enabled/disabled settings in AlDente:
 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected?
 - MacBook used in Clamshell Mode (with the lid closed)?

**Describe the bug**

**To Reproduce**

**Expected Behavior**

**Screenshots and Screen Recordings**
If applicable, add screenshots or screen recordings of the issue to help explain your problem.

**Additional context**
<img width="489" alt="Snipaste_2024-07-15_19-15-05" src="https://github.com/user-attachments/assets/fca9e78d-14e5-4207-9b3f-f19840f244fc">
Unable to install helper, My OS is Big sur

**Comment by MatthiasKerbl** [comment]
Hi @kuyvub,

Please fill out the questions above so we can better assess your issue.

Best,
Matthias

**Comment by kuyvub** [comment]
Thank you for getting back to me so quickly.
<img width="633" alt="Snipaste_2024-07-15_19-32-18" src="https://github.com/user-attachments/assets/79d7ad47-ea81-4cf5-a619-a4f232ff509f">
After entering the password and installing the auxiliary program, it shows that it is successful but in fact it is not successfully installed, it does not work, the pop-up interface is my screenshot like this, the previous old version did not have this problem, and it cannot be used after updating to the latest version
<img width="559" alt="Snipaste_2024-07-15_19-38-08" src="https://github.com/user-attachments/assets/91e928c5-d79e-436d-9090-35e9029d0737">

**Comment by kuyvub** [comment]
<img width="772" alt="Snipaste_2024-07-15_19-44-30" src="https://github.com/user-attachments/assets/f32c14fd-4a2f-4261-83b4-36a28417cb00">
Big sur is not supported now?Is more setup is required?Please tell me because this software is very useful

**Comment by kuyvub** [comment]
Back to the old version，Hope you fix this problem in the future
