### ISSUE TITLE
Maximum capacity dropped significantly after using AlDente for a week?

### ISSUE THREAD

**Issue by baomdg** [AppHouseKitchen/AlDente-Charge-Limiter#1275]
I've been using AlDente for a week and set the limit at 75%.

When I downloaded AlDente, on the Stats section it shown that my Maximum Capacity of Battery Health is fluctuated around 97% and 98% (while on the Macbook Maximum Capacity is still 100).

However, after using AlDente for a week, I've just checked the Maximum Capacity on the app and saw that it dropped from 97%-98% to 93%!

I don't know if I'm using AlDente wrong or I don't understand about the Maximum Capacity feature of it. But it makes me very confused.

Please nicely enlighten me!

**Comment by MatthiasKerbl** [comment]
Hi @baomdg,

I have already answered your question in the discussions section. Therefore, I will close this issue.

Best,
Matthias
