### ISSUE TITLE
https://apphousekitchen.com/license-agreement-free-version/ is a 404.

### ISSUE THREAD

**Issue by fragmede** [AppHouseKitchen/AlDente-Charge-Limiter#1278]
https://apphousekitchen.com/license-agreement-free-version/ is currently giving a 404 page and I can't agree to the validity of a licence agreement that doesn't exist.

**Comment by SidSidSid16** [comment]
I think this is related to an already open issue: https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/issues/1223

**Comment by fragmede** [comment]
dammit i searched. apologies for the noise.
