### ISSUE TITLE
Charge limit not enforced when shut down or in Bootcamp Windows

### ISSUE THREAD

**Issue by SidSidSid16** [AppHouseKitchen/AlDente-Charge-Limiter#1279]
- **MacBook Model:** MacBookPro14,3
 - **macOS Version:** Ventura 13.6.7
 - **Charger Model:** Apple OEM 87W
 - **Charging Cable:** Apple OEM USB-C
 - **AlDente Pro or AlDente Free:** Free
 - **AlDente Version:** 1.27.3
 - **List or add screenshots of all enabled/disabled settings in AlDente:** Launch at login enabled, everything in the "Charge" table disabled (not available in Free), everything in the "Features" tab disabled (not available in Free), 
 - **External Monitor connected?** No
 - **MacBook used in Clamshell Mode (with the lid closed)?** No

**Description**
Since the 1.27 update, I have noticed that although the battery percentage does not exceed the charge limit in macOS, as soon as I shut down or boot into Bootcamp Windows, the battery starts charging to full.

**Comment by MatthiasKerbl** [comment]
Hi @SidSidSid16,

I have explained these scenarios in the following issue #1250 

> "Due to the unified charging backend and our attempt to streamline the user experience of AlDente throughout all MacBook models, the Intel Mode is gone now, and the automatic persistent charge limit is therefore only available with AlDente Pro. Suppose you want the charge limit to persist during Bootcamp. In that case, you can consider getting AlDente Pro for the automatic persistent charge limit or downgrading to AlDente 1.26.1 and continue manually using the Intel Mode.
> You can get AlDente Pro on our [website](https://apphousekitchen.com/) and AlDente 1.26.1 on [GitHub](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/releases/tag/1.26.1)."

Best,
Matthias
