### ISSUE TITLE
Battery Limit not working on Bootcamp Windows 11 

### ISSUE THREAD

**Issue by frewper** [AppHouseKitchen/AlDente-Charge-Limiter#1305]
I have been Using Bootcamp with Windows 11 and am plagued with the battery issue. I have been trying AlDente to limit the battery charge, but alas it only works on the MacOS and when I restart into windows it doesnt work and charges the battery to 100%. (Limit set at 70%). I am using Version 1.27.3 which means that Intel Mode is removed. Only thing I am using AlDente Free, so I am not sure if this is a version issue.

If it not a version issue, what am I missing ?

 - MacBook Pro 2019 16" 
 - macOS Version 14.5 (23F79)
 - Apple Charger Factory
 - USB-C, Apple
 - AlDente Free:
 - AlDente Version: 1.27.3 
 - External Monitor connected -- YES

**Comment by MatthiasKerbl** [comment]
Hi @frewper,

The automatic persistent charge limit in Bootcamp is only available in AlDente Pro. Therefore, you have two options: Firstly, you can downgrade to [AlDente Free 1.26.1](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/releases/tag/1.26.1) and prohibit charging through the legacy feature Intel Mode. Secondly, you can buy AlDente Pro and enjoy the automatic charge limit in Bootcamp on top of all the other Pro features.

Best,
Matthias
