### ISSUE TITLE
Display of the possible charger output

### ISSUE THREAD

**Issue by cwerner1** [AppHouseKitchen/AlDente-Charge-Limiter#1307]
**Is your feature request related to a problem? Please describe.**
I have different Power Chargers - with different Output, also some USB-C Cable are only capable of 60W or 90 Watt Power Transfer.

In `SystemInformation` -> Hardware -> Power supply  the charger information is displayed, including the power.
<img width="264" alt="image" src="https://github.com/user-attachments/assets/51359838-03ca-4908-bb13-8bf256c6ab9c">

**Describe the solution you'd like**
It would be nice if Ardent could show this Entry.-
Under Statistics show the Power Available of the Charge - inside the Sendor Data and in the Powerflow.

**Describe alternatives you've considered**

**Additional context**
I used BatteryStatusShow before to view this value:
https://github.com/sicreative/BatteryStatusShow

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.29, which has a new "Power Adapter Specs" section within the Sensor Data Panel. To get AlDente 1.29 you just need to update within the app under Settings/General/Check for Updates.

Best,
Matthias
