### ISSUE TITLE
Losing functions of Remove Icon on Dock

### ISSUE THREAD

**Issue by JarrettChen217** [AppHouseKitchen/AlDente-Charge-Limiter#1310]
Recently I noticed that AlDente's icon had changed, so I went to adjust it, but the icon on the dock was appeared. and according to the FAQ I couldn't find a way to turn it off in Appearance. Also I noticed that some of the things in the Other section have disappeared, how can i fix it?
I tried to reinstall and restart my laptop, but issue stays the same.

* Apple M2 Pro, 14.6.1 (23G93)

<img width="884" alt="Screenshot 2024-09-04 at 12 28 44 PM" src="https://github.com/user-attachments/assets/6b51658a-6257-4805-b6ee-d935618553ff">

**Comment by MatthiasKerbl** [comment]
Hi @JarrettChen217,

Thank you for reporting this bug. It will be fixed soon.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @JarrettChen217 ,

We have just released AlDente 1.29, which includes a fix for this issue. To get AlDente 1.29 you just need to update within the app under Settings/General/Check for Updates.

Please report back if it works for you.

Best,
Matthias
