### ISSUE TITLE
MacBook not sleeping while discharging in Calibration Mode

### ISSUE THREAD

**Issue by UsamaKarim** [AppHouseKitchen/AlDente-Charge-Limiter#1317]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608): **MacBook Air (M1, 2020)**
 - macOS Version (https://support.apple.com/en-us/HT201260): **14.16.1**
 - Charger Model (Apple, Third Party, Wattage,...): **Apple / 30 W**
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): **USB-C**
 - AlDente Pro or AlDente Free: **AlDente Pro**
 - AlDente Version: **1.28.2**
 - List or add screenshots of all enabled/disabled settings in AlDente:
![Screenshot 2024-09-10 at 1 18 45 PM](https://github.com/user-attachments/assets/30186647-1970-4bf7-8352-b91908493b7e)
![Screenshot 2024-09-10 at 1 18 59 PM](https://github.com/user-attachments/assets/d7ebc1e3-fae1-4fa9-ae79-4f010f3d65b6)
![Screenshot 2024-09-10 at 1 19 43 PM](https://github.com/user-attachments/assets/eb30bd47-2105-4e29-be04-935897e5c613)

 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/). 
[aldentepro-debug-2024-09-10-13:14:23.pasta.zip](https://github.com/user-attachments/files/16941774/aldentepro-debug-2024-09-10-13.14.23.pasta.zip)

 - External Monitor connected? **Yes**
 - MacBook used in Clamshell Mode (with the lid closed)? **No**

**Describe the bug**
Discharging is common behaviour for OS, while Al Dente is in calibration mode and discharging and laptop is connected with charger, the laptop screen & external monitor screen remains, means sleep mode is not working. I reinstall the helper, it turned of calibration mode and the sleep started working again.

**To Reproduce**
1. Turn on Calibration Mode
2. Wait for discharging step
3. Lock the screen
4. The screen remain on for infinity (Sleep is not working

**Expected Behavior**
The screen should turn of and sleep mode should be working.

**Comment by MatthiasKerbl** [comment]
Hi @UsamaKarim,

This is the intended behavior of the Calibration Mode. You can read more about the background of this behavior in the following blog articles:

- [When Does AlDente Disable Sleep on MacBooks?](https://apphousekitchen.com/when-does-aldente-disable-sleep-on-macbooks/)
- [Feature Explanation: Calibration Mode](https://apphousekitchen.com/feature-explanation-calibration-mode-2/)

Best,
Matthias
