### ISSUE TITLE
Last version to support Macbook Pro Retina late 2012

### ISSUE THREAD

**Issue by polpas** [AppHouseKitchen/AlDente-Charge-Limiter#1320]
Hi there,

May you please tell me which is the last version of AlDente that support Macbook Pro late 2012?

**Comment by MatthiasKerbl** [comment]
Hi @polpas,

This version of AlDente should work on your device. (https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/releases/tag/1.2)
Please keep in mind that this is one of the first versions of AlDente and is unfortunately not reliable and bug-free.

Best,
Matthias
