### ISSUE TITLE
the charge indicator is broken macOS Sequoia

### ISSUE THREAD

**Issue by DruChill** [AppHouseKitchen/AlDente-Charge-Limiter#1330]
- MacBook Model (https://support.apple.com/es-es/111883): MacBook Air M1
 - macOS Version (https://support.apple.com/en-us/109033): macOS Sequoia
 - Charger Model (Apple, Third Party, Wattage,...): Apple
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): USB-C by Apple
 - AlDente Pro or AlDente Free: Pro
 - AlDente Version: 1.28.2

**Describe the bug**
This has already happened since I updated to version 1.28.2 from macOS Sonoma when the loading was paused it didn't show anything or I didn't remember well

- debug file (https://www.mediafire.com/file/wg265carb7mn2ph/aldentepro-debug-2024-09-18-08-52-24.pasta/file)
<img width="405" alt="Captura de pantalla 2024-09-18 a la(s) 08 56 25" src="https://github.com/user-attachments/assets/c2a4d34a-ed0a-4626-b17c-0f847fb6895e">

**Comment by MatthiasKerbl** [comment]
Hi @DruChill,

Thank you for your feedback. Currently, we are using the time to full value provided by macOS. Unfortunately, this metric does not show any reasonable values during discharging or when charging is paused.
We will try to improve it with the next updates.

Best,
Matthias
