### ISSUE TITLE
Remove app icon from dock while active

### ISSUE THREAD

**Issue by silasnevstad** [AppHouseKitchen/AlDente-Charge-Limiter#1333]
While the app is active the dock icon is shown and can't be removed.

Is it possible to add a feature to hide the dock icon so only the menu bar is shown?

**Comment by MatthiasKerbl** [comment]
Hi @silasnevstad,

You can hide the dock icon by opening the Settings/Appearance/Show Dock Icon - Disabled.

Best,
Matthias
