### ISSUE TITLE
Charging time shows time till 100% charged and not the set limit

### ISSUE THREAD

**Issue by LURSU-MiR** [AppHouseKitchen/AlDente-Charge-Limiter#1338]
**Describe the bug**
When charging the Mac, the time until fully charged shows the time till the Mac is charged to 100% and not the set limit.

**Comment by MatthiasKerbl** [comment]
Hi @LURSU-MiR,

Great idea. We already have a feature request open for this here #1200 and will give updates over there.

Best,
Matthias
