### ISSUE TITLE
Cannot Update to Newer Version of AlDente Pro 1.28.6 

### ISSUE THREAD

**Issue by By-pass** [AppHouseKitchen/AlDente-Charge-Limiter#1359]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608): Macbook Pro 16 (Apple M2) 
 - macOS Version (https://support.apple.com/en-us/HT201260): Ventura 13.7 (22H123)
 - AlDente Pro or AlDente Free: Pro
 - AlDente Version: 1.28.5
 - External Monitor connected?: No
 - MacBook used in Clamshell Mode (with the lid closed)?: No

**Describe the bug**
The update keeps failing (from 1.28.5, updating to 1.28.6). I have tried restarting Mac and AlDente, but it did not solve the issue. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Setting
2. Click on Update
3. Download the update (1.28.6)
4. Error - Could not successfully update due to an error from unpacking the update files. 

![Screenshot 2024-10-30 오후 1 58 37](https://github.com/user-attachments/assets/ab4f2017-44fe-43e8-9da7-c27349a8e85c)

Thank you for your time and help.

**Comment by MilesTEG1** [comment]
Hello,
I've got the same problem (I think, because I don't understand the text in the screenshot posted by @By-pass).

![CleanShot 2024-10-30 at 21 44 08@2x](https://github.com/user-attachments/assets/41eef478-7b85-4b0c-98a8-82fe2a5f425e)

**Comment by MilesTEG1** [comment]
I managed to update by using the `brew upgrade aldente` command.
It removed the old app, and installed the new one.
After reinstalling the Assistant, all good.

**Comment by amit-bh** [comment]
This is the error I am getting:

<img width="431" alt="Screenshot 2024-10-30 at 21 55 24" src="https://github.com/user-attachments/assets/39947b02-5d8d-4c24-9839-0d8d679ce136">

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Thank you very much for reporting this issue. Unfortunately, we cannot reproduce it (yet) but we are looking into it.
If possible, please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on [How to generate and share a debug file](https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/) on our blog.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We were able to resolve this issue. You should now be able to update AlDente without any issues.

Thank you for your patience.

Best,
Matthias
