### ISSUE TITLE
Show Time remaining

### ISSUE THREAD

**Issue by dags170291** [AppHouseKitchen/AlDente-Charge-Limiter#1360]
Hi, I love al Dente but one tiny little feature seems to be missing. I wish it had the ability to show time remaining on charge. please add this

**Comment by MatthiasKerbl** [comment]
Hi @dags170291,

Glad to hear you are a fan of AlDente.
Have you already updated to our newest version, AlDente 1.28.6?
This version will show "Time remaining" while in Discharge or unplugged.

Best,
Matthias

**Comment by dags170291** [comment]
Ahhhh silly me i did not check for updates. thank you so much
