### ISSUE TITLE
Hello, I purchased AIdente pro, why didn't I receive the license code?

### ISSUE THREAD

**Issue by marcusvramos** [AppHouseKitchen/AlDente-Charge-Limiter#1368]
I recently purchased an annual license for AlDente Pro using the email marcusramos651@gmail.com with a Mastercard. However, I haven’t received the license via email yet, despite it being about 1 day and some hours since I completed the purchase.

Could you please look into this and let me know when I can expect to receive the license?

I already sent an email to assistir@paddle.com. It's been over a day, but I haven't received any response.

**Comment by MatthiasKerbl** [comment]
Hi @marcusvramos,

You had a typo in your email address. I have just forwarded the purchasing emails to marcusramos651@gmail.com.

Best,
Matthias
