### ISSUE TITLE
After shutting down the mac with the power button, it loses the license key and most configuration.

### ISSUE THREAD

**Issue by ivanhernandez-dev** [AppHouseKitchen/AlDente-Charge-Limiter#1382]
**Describe the bug**
After shutting down the mac with the power button, it loses the license key and most configuration.

**To Reproduce**
1. Shutdown your Mac holding the power button
2. Turn it back on
3. Wait until aldente starts at login
4. Aldente has lost license and configuration

**Comment by MatthiasKerbl** [comment]
Hi @ivanhernandez-dev,

I am sorry to hear you are facing issues with AlDente.
Which AlDente Version do you use? If it is not 1.29, the newest one, please install this one and let me know if you still run into this issue.

Best,
Matthias

**Comment by ivanhernandez-dev** [comment]
Thank you for your prompt reply @MatthiasKerbl . I was using version 1.28.4, and after updating to 1.29, I haven’t been able to reproduce the issue.

You can go ahead and close this for now. If the problem occurs again, I’ll reopen it.

Apologies for any inconvenience caused.
