### ISSUE TITLE
Missing localized literals

### ISSUE THREAD

**Issue by andreuBiset** [AppHouseKitchen/AlDente-Charge-Limiter#1385]
**MacBook (please complete the following information):**
 - AlDente Pro or AlDente Free: **Pro**
 - AlDente Version: 1.28.4

**Describe the bug**
All labels and text are showing the key, not the localized text, maybe because I am using a not supported language (Catalan). 

**To Reproduce**
1. Open any modal or window
2. See the key of labels instead of localized text

**Expected Behavior**
If system language is not supported, use English as default language.

**Screenshots and Screen Recordings**

![screenshot_2024-11-24_144006](https://github.com/user-attachments/assets/d2e7b5a7-b60e-48e2-8cd5-4b952c22bfe5)
![screenshot_2024-11-24_144018](https://github.com/user-attachments/assets/d285d4ce-5dfa-4c7b-b521-a07cb8fea15e)
![screenshot_2024-11-24_144023](https://github.com/user-attachments/assets/f9bd7395-4358-480b-8efd-2311ffa57b73)

**Additional context**
I have AldentePro with SetApp https://setapp.com (Version 3.42.0)

**Comment by MatthiasKerbl** [comment]
Hi @andreuBiset,

Thank you for notifying us about this issue. We will try to fix it as soon as possible.
For now, you should be able to fix it by following this [tutorial](https://apphousekitchen.com/step-by-step-guide-change-language-for-a-single-app-on-macos/).

Best,
Matthias

**Comment by andreuBiset** [comment]
HI @MatthiasKerbl,

Thank you! After restarting, Setapp updated AlDente to version 1.29, and now the texts are displaying correctly:

![screenshot_2024-11-24_154853](https://github.com/user-attachments/assets/af7d2475-e3fd-4a16-9f24-185d05906074)
![screenshot_2024-11-24_154854](https://github.com/user-attachments/assets/ce59e092-2ff1-4eba-85a2-3eb1f0fd809a)
