### ISSUE TITLE
My system version is macOS 12.2.1, running on an M1 chip, and currently, the installation of the auxiliary program is unresponsive.

### ISSUE THREAD

**Issue by AdminYlc** [AppHouseKitchen/AlDente-Charge-Limiter#1390]
Hello

MacBook

AlDente Pro 1.27
Macbook Air M1

<img width="421" alt="79CA228C-61BA-4BBC-AAC2-5DC3AE37AB62" src="https://github.com/user-attachments/assets/4a5d0446-9aff-4bd5-b886-911ef1256f35">

Bug
The installation of the auxiliary program shows no response at all.

**Comment by MatthiasKerbl** [comment]
Hi @AdminYlc,

Please follow our [uninstallation guide](https://apphousekitchen.com/how-to-uninstall-aldente-pro/).
Afterward, download and install AlDente again.

Best,
Matthias

**Comment by AdminYlc** [comment]
This issue was resolved by completely uninstalling and reinstalling the program. However, the problem occurred suddenly without any warning and has happened twice. I hope the team can investigate the root cause.

**Comment by MatthiasKerbl** [comment]
Hey @AdminYlc,

Good to hear that you could fix it. We will try to improve on this matter with future updates.

Best,
Matthias
