### ISSUE TITLE
Active Discharge in Clamshell Mode is only available with the Pro version

### ISSUE THREAD

**Issue by HermanTam** [AppHouseKitchen/AlDente-Charge-Limiter#1391]
**MacBook (please complete the following information):**
 - MacBook Model (MacBook Pro 16-inch, 2019):
 - macOS Version (Version 15.0 (24A335)):
 - Charger Model (Usb-c to Usb-c video cord to an LG external monitor):
 - Charging Cable (third party Usb-c to Usb-c video cord to an LG external monitor):
 - AlDente Free:
 - AlDente Version: Latest[AlDente 1.29]
 - List or add screenshots of all enabled/disabled settings in AlDente:
![image](https://github.com/user-attachments/assets/043e318a-c1a3-4282-b6e5-a27bc738476f)
![image](https://github.com/user-attachments/assets/8b945896-f51d-4acf-8706-1eba9b0e9c42)
![image](https://github.com/user-attachments/assets/294037e0-c8d7-4e43-8cd6-1e7278b7cb84)
![image](https://github.com/user-attachments/assets/43355d51-abec-4a98-a4d0-cd97aea4ad1c)
![image](https://github.com/user-attachments/assets/ab5c2ee6-f297-4598-ac55-accb13f914c3)
![image](https://github.com/user-attachments/assets/810fc720-8fc4-44cc-8cea-5fe9d9adcb92)

 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - 
![image](https://github.com/user-attachments/assets/52e258a4-0107-4bfb-9ee0-2362eb30d9c6)

 - External Monitor connected? Yes 
 - MacBook used in Clamshell Mode (with the lid closed)? Yes

**Describe the bug**

**To Reproduce**
1. Go to 'AlDente'
2. Click on 'Discharge'
3. See error

**Expected Behavior**

**Screenshots and Screen Recordings**
If applicable, add screenshots or screen recordings of the issue to help explain your problem.

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @HermanTam,

As described in the screenshot of the AlDente notification, the Discharge feature during Clamshell mode is only available with AlDente Pro. This is mainly due to the long development time to get Discharge to work during Clamshell mode.

Best,
Matthias
