### ISSUE TITLE
Updated to macOS 15.2 and it's not working properly aldente

### ISSUE THREAD

**Issue by DruChill** [AppHouseKitchen/AlDente-Charge-Limiter#1395]
- MacBook Model (https://support.apple.com/es-es/111883): MacBook Air M1
 - macOS Version (https://support.apple.com/en-us/109033): macOS Sequoia 15.2
 - Charger Model (Apple, Third Party, Wattage,...): Apple
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): Other
 - AlDente Pro or AlDente Free: Pro
 - AlDente Version: 1.29

**Describe the bug**
Since I updated to macOS sequoia 15.2 it doesn't work correctly aldende it doesn't stop the power well and when I disconnect it it still has the paused loading icon there are many errors help please I'm pro version, the .paste file here:

- debug file (https://www.mediafire.com/file/g5f1utx3oievyoa/aldentepro-debug-2024-12-15-09-19-50.pasta/file)

**Comment by DruChill** [comment]
Apparently I think my adapter is starting to fail and could be the cause of this problem. In any case, my .past file could be useful

**Comment by DruChill** [comment]
Apparently so, but I think the other entry on the Mac has gone bad and I'm using the other one, it's still a mystery.

**Comment by MatthiasKerbl** [comment]
Hi @DruChill,

MacOS 15.2 is working without any issues on all of our devices.
Going through your debug file, I see that the issue seems to be somewhere in the power delivery (charger, cable, plug).

Best,
Matthias

**Comment by DruChill** [comment]
If you are absolutely right, it seems that the entry of my MacBook failed 😞
