### ISSUE TITLE
No Confirmation of Vulnerability Submission After 5 Days

### ISSUE THREAD

**Issue by senzee1984** [AppHouseKitchen/AlDente-Charge-Limiter#1396]
Hi, last week, I followed the security policy and submitted a vulnerability through email. According to the security policy, the acknowledgement was expected within 48 hours. However, after 5 days, I still did not receive a confirmation of the submission.

I just want to make sure the submission was delivered successfully. thanks.

**Comment by MatthiasKerbl** [comment]
Hi @senzee1984,

Thank you for your vulnerability submission. We have already responded a couple of days ago but it seems you haven't gotten the reply. Anyway, we have replied again. Let us know if you are still not getting the emails.

Best,
Matthias
