### ISSUE TITLE
[Feature Request] More Battery Information - Suggestion for inclusion in Pro Version

### ISSUE THREAD

**Issue by mikebore** [AppHouseKitchen/AlDente-Charge-Limiter#250]
I expect many people who care enough about batteries will have installed some or all of Coconut, Better Battery 2, or Battery Monitor. All of these utilities provide extra info extracted from the system by the ioreg command (_ioreg -w 0 -f -r -c AppleSmartBattery_). Particularly interesting to me is the current max capacity or Health %. None of them provide any control like AlDente.

How about incorporating some or all of this info into AlDente to make it the all-can-do Battery app?...removing the need for any others.

**Comment by AppleRobert** [comment]
Excellent idea, Mike.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.25 which includes a new widget for battery data. The new data widget can be activated in the stats category of in the settings. To get AlDente 1.25 you just need to update within the app under Settings/General/Check for Updates.

Best,
Matthias
