### ISSUE TITLE
[Feature Request] Show timestamp of last successful calibration

### ISSUE THREAD

**Issue by retrospct** [AppHouseKitchen/AlDente-Charge-Limiter#575]
As a user I'd like to know when the last successful calibration cycle happened.

I actually feel like this update with the `Automatic Calibration` feature request #572 will make a huge improvement. Thanks!

I made some quick mockups to display the idea:
1. Display time since last successful calibration.
2. Display time since in the menubar UI.
3. Move the settings sprocket button down to balance the UI from adding more space for the time since text.
![image](https://user-images.githubusercontent.com/1510356/151619711-8fedaa0f-e22f-4539-8594-489c4e4a65d0.png)
![image](https://user-images.githubusercontent.com/1510356/151619772-e1a2c862-d281-44fa-a62e-91629e36672e.png)

**Comment by MatthiasKerbl** [comment]
Hi @retrospct,

That’s a good idea and thank you for the mockups.
We will try to implement some kind of timer since the last calibration.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @retrospct,

Unfortunately, not a timer yet but our newest version AlDente 1.21.1 has a new beta feature called Schedule. This feature allows users to set specific Actions in AlDente to run automatically on predetermined days, times, and intervals. For example, Calibration Mode can be set to run every two weeks.
You can read more about the Schedule feature and its current limitations here: https://apphousekitchen.com/feature-explanation-schedule/
You can find a full list of the Release Notes here: https://apphousekitchen.com/changelog/

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @retrospct,

We have just released AlDente 1.28.1 which now shows the last successful calibration in the settings window. To get AlDente 1.28.1 you just need to update within the app under Settings/General/Check for Updates.
Please report back if it works for you.

Best,
Matthias
