### ISSUE TITLE
Added progress bar for calibration mode

### ISSUE THREAD

**Issue by kentzh1** [AppHouseKitchen/AlDente-Charge-Limiter#585]
I don't know if it is difficult to develop, because during the charging and discharging calibration process, everyone will not always pay attention to the progress of the whole process, and it may cause confusion before it is completed; my suggestion is whether to add a progress bar in the calibration mode, In addition to being beautiful, it is also very intuitive to see the progress of the current battery calibration.
<img width="599" alt="WeChat627c297150193ed8f74f40640f6c4b61" src="https://user-images.githubusercontent.com/67768011/152688972-96263b64-1b2b-4a69-b09b-1a8c406a14a9.png">

**Comment by stat11** [comment]
this is good advice！

**Comment by ovq** [comment]
adding to this feature set:
- show in calibration settings when the last fully executed calibration happened.
- ability to set a reminder to calibrate - maybe even taking "time connected to power" into account
