### ISSUE TITLE
[Feature Request] Show Current Battery Temperature in Al Dente Popup Window

### ISSUE THREAD

**Issue by mitchellisdumb** [AppHouseKitchen/AlDente-Charge-Limiter#620]
**Is your feature request related to a problem? Please describe.**
It takes a few clicks to see the current battery temperature.

**Describe the solution you'd like**
I would like the status readout in the Al Dente popup window to include the current battery temperature.

**Describe alternatives you've considered**
I could install iStatMenus or similar.

**Additional context**

**Comment by Stickyhavr** [comment]
I agree. Currently you have to dig down into Settings then Charge Settings just to see the current temp. It would be great if you could see it on the first click of the menu bar. Or, optionally, have it displayed in the menu bar along with the status and percentage, as requested in #489

**Comment by basmets6** [comment]
+1 on this one

**Comment by rusteze89** [comment]
+1 on this particularly now that there is the option to display Power Flow. The Stats menu could have the option of displaying Power Flow **and Temperature** on the popup window.
