### ISSUE TITLE
More information about Battery

### ISSUE THREAD

**Issue by Volodymyr-13** [AppHouseKitchen/AlDente-Charge-Limiter#658]
**Is your feature request related to a problem? Please describe.**
I'm looking for more technical information about battery: 

- Design Capacity - xxxx mAh
- Full Charge Capacity - xxxx mAh
- Manufacture date
- Age
- Cycle Count
- Power adapter(Connected) - XX Watts
- any other useful info

For Menu Bar icon:
- Show temperature
- Show wattage
- Show voltage
- Show amperage

**Describe the solution you'd like**
Since this app is all about Battery of my MacBook, so I think it should provide me more technical info about it.
For example: 

<img width="203" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/3391456/163175236-6feca0a5-20e5-4b0f-8517-02f67f438b5c.png"> <img width="195" alt="Screen Shot" src="https://user-images.githubusercontent.com/3391456/163175899-bd66aa9c-c6fd-4ef6-bb83-dfc8d1e55da5.png"><img width="547" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/3391456/163176159-edd13795-4876-4af3-a37f-ccb870fc6d53.png"> 

All this could be added into **contextual menu** on the app: 
<img width="222" alt="menu" src="https://user-images.githubusercontent.com/3391456/163176074-0bd3b1c3-6581-4624-aabe-cd26a8c36f30.png">

And into the **Menu Bar icon**:

<img width="243" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/3391456/163176384-6b31dc17-e332-4c04-a6fe-fe3969be3707.png">

**Describe alternatives you've considered**
coconutBattery, Wattagio

**Comment by andrewcrook** [comment]
you missed one showing battery level as estimated time

**Comment by andrewcrook** [comment]
same as #250

**Comment by KAMIKAZEUA** [comment]
@MatthiasKerbl perhaps should be useful https://github.com/sicreative/BatteryStatusShow

**Comment by andrewcrook** [comment]
@KAMIKAZEUA

You have to be a bit careful you cannot just go around copying stuff. 
Open source is still licensed  and this is freemium with comcerial option.

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl perhaps should be useful https://github.com/sicreative/BatteryStatusShow

Hi @KAMIKAZEUA,

Thank you, will check it out.

**Comment by MatthiasKerbl** [comment]
> @KAMIKAZEUA
> 
> You have to be a bit careful you cannot just go around copying stuff. Open source is still licensed and this is freemium with comcerial option.

Hi @andrewcrook,

Just wanted to say that we take open-source licenses seriously and would not just copy code from other projects without permission.

Cheers,
Matthias

**Comment by andrewcrook** [comment]
@MatthiasKerbl 

Of course and I am sorry if it sounded otherwise.
I was just commenting on the number of posts where people are wanting features from other applications and that it is not always that easy or possible to fulfil.

**Comment by KAMIKAZEUA** [comment]
@andrewcrook that ioreg info is the same for all apps, so retrieving code will be the same too. I just pointed to that app, which already have this implemented, so should be easily taken as example.

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl
> 
> Of course and I am sorry if it sounded otherwise. I was just commenting on the number of posts where people are wanting features from other applications and that it is not always that easy or possible to fulfil.

Hi @andrewcrook,

All good and thank you for raising awareness for this since it is not clear to most people.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.25 which includes a new widget for battery data. The new data widget can be activated in the stats category of in the settings. Also, this feature will be updated in the future to include even more data. To get AlDente 1.25 you just need to update within the app under Settings/General/Check for Updates.

Best,
Matthias

**Comment by Volodymyr-13** [comment]
@MatthiasKerbl 

I just tried to update..

![Screenshot 2](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3391456/cf0ae2ff-3849-4eca-b196-d64ce3523292)

**Comment by Volodymyr-13** [comment]
@MatthiasKerbl ok it works, I like it but not fully, since I wanted actually this(this is from first post of this issue): 


![](https://user-images.githubusercontent.com/3391456/163176384-6b31dc17-e332-4c04-a6fe-fe3969be3707.png)

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl
> 
> I just tried to update..
> 
> https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3391456/cf0ae2ff-3849-4eca-b196-d64ce3523292
> 
> Upd.: did manual download from site.

Hi @Volodymyr-13,

Thanks for letting us know. The update functionality is fixed now.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl ok it works, I like it but not fully, since I wanted actually this(this is from first post of this issue):
> 
> ![](https://user-images.githubusercontent.com/3391456/163176384-6b31dc17-e332-4c04-a6fe-fe3969be3707.png)

Hi @Volodymyr-13,

Thank you for your feedback, we will consider it in the ongoing development and improvement of AlDente.

Best,
Matthias

**Comment by Volodymyr-13** [comment]
@MatthiasKerbl looking forward into this. 

Also, you could add maybe some nice progress bars, to be more catchy and finally fix this(https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/issues/678) and so I could finally not to use Wattagio and just use this app alone)



![Screenshot](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3391456/ee2127dd-0b7b-4e86-b60b-0d0d08bec096)![Screenshot 1](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3391456/019cd719-6b27-4aa7-95ed-2c8295d10e38)

**Comment by Volodymyr-13** [comment]
> Hi @Volodymyr-13,
> 
> Thank you for your feedback, we will consider it in the ongoing development and improvement of AlDente.
> 
> Best, Matthias

Any updates on this? 
I wish to add a System Load **W** same as Wattagio doing: 

![Screenshot 1](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3391456/ac4d9b5c-c94c-4320-9f2d-39c240085676)
![Screenshot 2](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/3391456/e7d49ca3-7d9f-400e-8d46-b51d783d6919)

**Comment by Volodymyr-13** [comment]
@MatthiasKerbl can you please Open this issue? 

Since my last message bellow is still what I want from AlDente, this is really easy task, since you already have implemented this information in popover, so just add this text into Menubar is easy.
