### ISSUE TITLE
Onboarding flow is skipped if app was updated during it

### ISSUE THREAD

**Issue by maxgashkov** [AppHouseKitchen/AlDente-Charge-Limiter#977]
**Describe the bug**
I've just purchased AlDente Pro and when I launched it, it started the dialog for the initial setup. However it also prompted me to update the app to the new version (I've downloaded the .dmg from the link in the purchase email), which I did immediately. When it was launched again, onboarding dialog was not shown anymore.

As a consequence, I never saw the instruction to turn off the system's optimized battery charging setting which is critical for the correct work of the app.

I think the need to turn the setting off should be displayed more prominently in the app's settings, so this may not be a bug but a feature request — please change the issue type accordingly if I mislabeled it.

**To Reproduce**
1. Install the app.
2. Click through the first step of the onboarding flow.
3. Update the app.
4. Open it again.
5. Onboarding is not shown anymore.

**Expected behavior**
Onboarding flow is displayed until it's completed.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 not relevant

 - macOS version (https://support.apple.com/en-us/HT201260)
 Ventura 13.4

 - AlDente Pro or AlDente Free?
 Pro

 - AlDente Version?
 1.22 (prior version that trigged the update is unknown)

**Comment by MatthiasKerbl** [comment]
Hi @maxgashkov,

First of all sorry for the late reply.
Thank you for making us aware of this matter. Unfortunately, it is not that easy to fix this. However, we have redirected the old download links to the newest version of AlDente to avoid this from happening in the future.

Best,
Matthias
