### ISSUE TITLE
When the pop-up is open, the menu bar auto-hides and moves the popup upwards

### ISSUE THREAD

**Issue by ADTC** [AppHouseKitchen/AlDente-Charge-Limiter#984]
**Describe the bug**
This is a slightly unique situation, as most macOS users don't enable menu bar auto-hide. _But I do._

The problem with Al Dente is that if its popup is open, the menu bar hides when I move the mouse away, pulling the popup upwards. This doesn't happen with any other icon in the menu bar (neither macOS built-in icon or a third party app icon), in which case the menu bar stays visible as long as the icon's popup menu is open.

**To Reproduce**
1. In Desktop & Dock (in System Settings), set "Automatically hide and show the menu bar" to "Always".
2. Open the AlDente pop-up by clicking its icon in the menu bar.
3. Move the mouse pointer away and observe.

**Expected behavior**
When the pop-up is open, the menu bar should remain visible even if the mouse is moved away. When the mouse is clicked somewhere else, the pop-up should close and the menu bar should hide away.

**Screenshots**
Pop-up opened:

<img width="408" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/6047296/c7145205-88a9-482b-94be-162445311acb">

Mouse moved away:

<img width="422" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/6047296/2cae9a4e-2d14-4e65-bec2-29f4b2cf3f43">

(You can see the pop-up moved upwards in relation to the window below, and the arrow is cut off. Although not captured here, the top-left corner is hidden by the camera notch.)

**MacBook:**
 - MBP 16" 2021 M1 Pro
 - Ventura 13.4 (22F66)
 - AlDente Free
 - 1.22
 - Mostly default. Show on startup and Dock icon are disabled.

**Additional context**
I'm just guessing here, but it could be because you're using some sort of custom container implementation for the pop-up instead of the standard menu container provided by Apple. I think the standard container could possibly include your custom contents in it, based on what I see with Apple's own Control Center and Now Playing widget:

<img width="326" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/6047296/4a11416d-56d3-4e4a-b85b-37fb7ac4d504">

<img width="394" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/6047296/e4a2645f-4478-448d-bc29-1aa7491262d4">

These don't hide the menu and move up when the mouse pointer is moved away.

**Comment by MatthiasKerbl** [comment]
Hi @ADTC,

You are right, I am experiencing the same issue. We will look into it and try to fix it with one of the next updates.

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @ADTC,

We have just released AlDente 1.28.1 which includes a fix for this issue. To get AlDente 1.28.1 you just need to update within the app under Settings/General/Check for Updates.
Please report back if it works for you.

Best,
Matthias
