### ISSUE TITLE
Screen stays on while lid is closed and "Disable sleep until charge limit" is active for Apple Silicon MacBooks

### ISSUE THREAD

**Issue by LackedMule1217** [AppHouseKitchen/AlDente-Charge-Limiter#998]
**Describe the bug**
The screen stays on even when lid is closed and "Disable sleep until charge limit" is active.

**To Reproduce**
1. Go to Settings
2. Click on 'Disable sleep until charge limit' and enable it
3. Close the MacBook lid
4. Screen still stays lit. This drains battery.

**Expected behavior**
When I close the lid, the screen should turn off to conserve battery. And after it has charged to the target percentage, it should auto-sleep.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.
<img width="413" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/42521926/2c958a8b-cf9b-4c14-b68a-e8fb760b59e5">

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608): A2779
 - macOS version (https://support.apple.com/en-us/HT201260): 13.4.1 (c)
 - AlDente Pro or AlDente Free?: AlDente Pro
 - AlDente Version?: 1.22
 - List of all enabled/disabled settings in AlDente:
<img width="427" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/42521926/375d0057-c8c5-4187-a408-40e7ad0dcc53">
<img width="421" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/42521926/908bb489-b0ad-4907-80f1-3fd3fe3af5bb">
<img width="428" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/42521926/20a6598e-2992-46c1-ac77-e63830543155">
<img width="422" alt="image" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/42521926/c0b063e1-525c-4baa-ac86-375b47299204">

**Comment by olasun** [comment]
Can confirm this, reproduced on a machine described below.

- MacBook model (https://support.apple.com/en-us/HT201300): A2442

- macOS version (https://support.apple.com/en-us/HT201260): 13.4.1 (c)

- AlDente Pro or AlDente Free?: AlDente Pro

- AlDente Version?: 1.22

No need for duplicating identical screenshots as they already are in the original post.

**Comment by dreit-p** [comment]
I'm really looking forward to the fix. I always find my laptop hot and not charged because of this bug.

**Comment by dreit-p** [comment]
I have a workaround for those who are facing the same problem. Use the [amphetamine app](https://apps.apple.com/us/app/amphetamine/id937984704?mt=12) to block sleep while charging. In AlDente itself, disable this feature.

**Comment by MatthiasKerbl** [comment]
Hi @LackedMule1217,

Good news, we have just released AlDente 1.27 which will now turn off the backlight of the display when the lid is closed and Disable Sleep Until Charg Limit is active.

Best,
Matthias
